In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("E:\AI Intern - Assessment\support_tickets.csv")

In [3]:
df.shape

(500, 10)

In [4]:
df.head()

,ticket_id,created_at,category,priority,status,response_time_hrs,resolution_time_hrs,agent_id,customer_rating,issue_summary
0,TKT-001,2024-02-05 11:14,General,Low,Resolved,3.7,7.8,AGT-03,4.0,Request for product documentation
1,TKT-002,2024-03-05 17:01,Billing,Low,Resolved,1.2,13.7,AGT-09,4.0,Incorrect charge on invoice
2,TKT-003,2024-02-13 12:09,Billing,High,Resolved,4.8,2.1,AGT-04,5.0,Unexpected fee on account
3,TKT-004,2024-03-09 09:59,Billing,High,Resolved,0.6,10.7,AGT-07,4.0,Subscription not activated after payment
4,TKT-005,2024-03-25 11:49,General,Low,Open,4.9,NaN,AGT-05,NaN,How to export data to CSV

In [5]:
df.columns

Index(['ticket_id', 'created_at', 'category', 'priority', 'status',
       'response_time_hrs', 'resolution_time_hrs', 'agent_id',
       'customer_rating', 'issue_summary'],
      dtype='object')

In [6]:
df.dtypes

ticket_id               object
created_at              object
category                object
priority                object
status                  object
response_time_hrs      float64
resolution_time_hrs    float64
agent_id                object
customer_rating        float64
issue_summary           object
dtype: object

In [7]:
df["created_at"] = pd.to_datetime(df["created_at"])

In [8]:
df["created_at"].dtype

dtype('<M8[ns]')

In [9]:
df.isnull().sum()

ticket_id                0
created_at               0
category                 0
priority                 0
status                   0
response_time_hrs        0
resolution_time_hrs    173
agent_id                 0
customer_rating        173
issue_summary            0
dtype: int64

In [10]:
df["ticket_id"].duplicated().sum()

np.int64(0)

In [11]:
df.nunique()

ticket_id              500
created_at             495
category                 3
priority                 4
status                   3
response_time_hrs       49
resolution_time_hrs    217
agent_id                12
customer_rating          5
issue_summary           26
dtype: int64

In [12]:
# Category, Priority and Status
print("Categories:")
print(df["category"].value_counts())

print("\nPriorities:")
print(df["priority"].value_counts())

print("\nStatuses:")
print(df["status"].value_counts())

Categories:
category
General      189
Billing      159
Technical    152
Name: count, dtype: int64

Priorities:
priority
Medium      169
Low         142
High        134
Critical     55
Name: count, dtype: int64

Statuses:
status
Resolved     327
Open         111
Escalated     62
Name: count, dtype: int64

In [13]:
# Duplicate Tickets

df["ticket_id"].duplicated().sum()

np.int64(0)

In [14]:
# Basic Statistics

df.describe()

,created_at,response_time_hrs,resolution_time_hrs,customer_rating
count,500,500.000000,327.000000,327.000000
mean,2024-02-16 17:00:32.040000,2.620600,19.158410,3.749235
min,2024-01-01 08:54:00,0.200000,1.200000,1.000000
25%,2024-01-24 10:41:15,1.400000,6.150000,3.000000
50%,2024-02-17 16:26:00,2.600000,12.000000,4.000000
75%,2024-03-11 08:42:00,3.900000,22.950000,5.000000
max,2024-03-30 18:06:00,5.000000,119.700000,5.000000
std,NaN,1.398753,20.042852,1.109686

In [15]:
# Response Time Statistics

df["response_time_hrs"].describe()

count    500.000000
mean       2.620600
std        1.398753
min        0.200000
25%        1.400000
50%        2.600000
75%        3.900000
max        5.000000
Name: response_time_hrs, dtype: float64

In [16]:
# Resolution Time Statistics

df["resolution_time_hrs"].describe()

count    327.000000
mean      19.158410
std       20.042852
min        1.200000
25%        6.150000
50%       12.000000
75%       22.950000
max      119.700000
Name: resolution_time_hrs, dtype: float64

In [17]:
# Tickets Handled by Each Agent

df["agent_id"].value_counts()

agent_id
AGT-09    50
AGT-12    49
AGT-07    47
AGT-11    47
AGT-06    46
AGT-01    46
AGT-08    42
AGT-02    40
AGT-04    37
AGT-10    35
AGT-03    34
AGT-05    27
Name: count, dtype: int64

In [18]:
# Average Customer Rating by Agent

df.groupby("agent_id")["customer_rating"].mean()

agent_id
AGT-01    3.870968
AGT-02    3.521739
AGT-03    3.875000
AGT-04    3.904762
AGT-05    3.823529
AGT-06    3.617647
AGT-07    3.925926
AGT-08    3.480000
AGT-09    3.810811
AGT-10    3.909091
AGT-11    3.482759
AGT-12    3.810811
Name: customer_rating, dtype: float64

In [19]:
# Average Customer Rating by Category

df.groupby("category")["customer_rating"].mean()

category
Billing      3.722772
General      3.778689
Technical    3.740385
Name: customer_rating, dtype: float64

In [20]:
# Average Resolution Time by Category

df.groupby("category")["resolution_time_hrs"].mean()

category
Billing      16.334653
General      20.278689
Technical    20.586538
Name: resolution_time_hrs, dtype: float64

In [21]:
# Tickets by Priority

df["priority"].value_counts()

priority
Medium      169
Low         142
High        134
Critical     55
Name: count, dtype: int64

In [22]:
# Tickets by Status

df["status"].value_counts()

status
Resolved     327
Open         111
Escalated     62
Name: count, dtype: int64

In [23]:
# Tickets by Category

df["category"].value_counts()

category
General      189
Billing      159
Technical    152
Name: count, dtype: int64

In [24]:
# Date Range

print("Start Date:", df["created_at"].min())
print("End Date:", df["created_at"].max())

Start Date: 2024-01-01 08:54:00
End Date: 2024-03-30 18:06:00

In [25]:
# Unresolved Tickets

df[df["status"] != "Resolved"].shape[0]

173

In [26]:
# Critical Unresolved Tickets

df[
    (df["priority"] == "Critical") &
    (df["status"] != "Resolved")
].shape[0]

31

In [27]:
# Unresolved High-Priority Tickets

df[
    (df["priority"] == "High") &
    (df["status"] != "Resolved")
].shape[0]

49

In [28]:
# Resolution Time by Status

df.groupby("status")["resolution_time_hrs"].mean()

status
Escalated         NaN
Open              NaN
Resolved     19.15841
Name: resolution_time_hrs, dtype: float64

In [29]:
# Resolution Time Missing by Status

df.groupby("status")["resolution_time_hrs"].apply(lambda x: x.isnull().sum())

status
Escalated     62
Open         111
Resolved       0
Name: resolution_time_hrs, dtype: int64

In [30]:
# Resolution Time Threshold

resolution_threshold = df["resolution_time_hrs"].quantile(0.95)

print("95th Percentile Resolution Time:", resolution_threshold)

95th Percentile Resolution Time: 60.11999999999998

In [31]:
# Abnormally Long Resolution Tickets

long_resolution_tickets = df[
    df["resolution_time_hrs"] > resolution_threshold
]

print("Number of unusually long resolution tickets:", len(long_resolution_tickets))

Number of unusually long resolution tickets: 17

In [32]:
# Long Resolution Tickets

long_resolution_tickets[
    [
        "ticket_id",
        "priority",
        "status",
        "resolution_time_hrs",
        "agent_id",
        "issue_summary"
    ]
]

,ticket_id,priority,status,resolution_time_hrs,agent_id,issue_summary
22,TKT-023,Low,Resolved,76.1,AGT-07,Payment failed but amount deducted
91,TKT-092,High,Resolved,84.2,AGT-11,API timeout errors in production
107,TKT-108,High,Resolved,119.7,AGT-07,Question about usage limits
127,TKT-128,Medium,Resolved,76.5,AGT-10,System login failure after update
129,TKT-130,Medium,Resolved,114.3,AGT-07,How to add team members
157,TKT-158,Medium,Resolved,87.3,AGT-10,Double billing issue
254,TKT-255,Critical,Resolved,66.6,AGT-06,Question about usage limits
279,TKT-280,Low,Resolved,72.7,AGT-04,Wrong plan charged
299,TKT-300,Medium,Resolved,77.5,AGT-09,Error 500 on checkout page
368,TKT-369,High,Resolved,119.6,AGT-11,Request for product documentation
378,TKT-379,High,Resolved,66.8,AGT-08,Question about usage limits
397,TKT-398,High,Resolved,66.1,AGT-11,Change notification preferences
399,TKT-400,Medium,Resolved,68.1,AGT-03,Dashboard not loading
408,TKT-409,High,Resolved,96.5,AGT-08,How to export data to CSV
445,TKT-446,Critical,Resolved,60.6,AGT-04,Database connection timeout
465,TKT-466,High,Resolved,100.4,AGT-08,API timeout errors in production
471,TKT-472,Low,Resolved,79.0,AGT-08,Integration broken after version upgrade

In [33]:
# High-Priority Unresolved Tickets

high_priority_unresolved = df[
    (df["priority"].isin(["High", "Critical"])) &
    (df["status"] != "Resolved")
]

print("High-priority unresolved tickets:", len(high_priority_unresolved))

High-priority unresolved tickets: 80

In [34]:
# Ticket Age

reference_time = df["created_at"].max()

df["ticket_age_hrs"] = (
    reference_time - df["created_at"]
).dt.total_seconds() / 3600

In [35]:
# High-Priority Tickets Older Than 24 Hours

old_high_priority = df[
    (df["priority"].isin(["High", "Critical"])) &
    (df["status"] != "Resolved") &
    (df["ticket_age_hrs"] > 24)
]

print("High-priority unresolved tickets older than 24 hours:", len(old_high_priority))

High-priority unresolved tickets older than 24 hours: 80

In [36]:
# High-Priority Tickets Older Than 24 Hours

old_high_priority = df[
    (df["priority"].isin(["High", "Critical"])) &
    (df["status"] != "Resolved") &
    (df["ticket_age_hrs"] > 24)
]

print("High-priority unresolved tickets older than 24 hours:", len(old_high_priority))

High-priority unresolved tickets older than 24 hours: 80

In [37]:
# Old High-Priority Tickets

old_high_priority[
    [
        "ticket_id",
        "created_at",
        "priority",
        "status",
        "ticket_age_hrs",
        "agent_id",
        "issue_summary"
    ]
]

,ticket_id,created_at,priority,status,ticket_age_hrs,agent_id,issue_summary
6,TKT-007,2024-01-21 15:24:00,High,Open,1658.700000,AGT-05,Question about usage limits
12,TKT-013,2024-03-05 09:55:00,High,Open,608.183333,AGT-11,Question about usage limits
21,TKT-022,2024-03-11 09:03:00,High,Open,465.050000,AGT-11,API timeout errors in production
43,TKT-044,2024-02-08 12:13:00,High,Open,1229.883333,AGT-07,Request for account deletion
57,TKT-058,2024-03-01 08:47:00,High,Escalated,705.316667,AGT-09,Integration broken after version upgrade
...,...,...,...,...,...,...,...
474,TKT-475,2024-01-24 10:18:00,High,Open,1591.800000,AGT-02,Unexpected fee on account
478,TKT-479,2024-02-01 14:49:00,Critical,Open,1395.283333,AGT-08,Subscription not activated after payment
479,TKT-480,2024-01-13 16:42:00,High,Open,1849.400000,AGT-04,Data sync not working
487,TKT-488,2024-03-20 11:20:00,High,Escalated,246.766667,AGT-12,How to add team members
495,TKT-496,2024-02-11 13:26:00,Critical,Escalated,1156.666667,AGT-11,Question about usage limits

In [38]:
# Old High-Priority Tickets

old_high_priority[
    [
        "ticket_id",
        "created_at",
        "priority",
        "status",
        "ticket_age_hrs",
        "agent_id",
        "issue_summary"
    ]
]

,ticket_id,created_at,priority,status,ticket_age_hrs,agent_id,issue_summary
6,TKT-007,2024-01-21 15:24:00,High,Open,1658.700000,AGT-05,Question about usage limits
12,TKT-013,2024-03-05 09:55:00,High,Open,608.183333,AGT-11,Question about usage limits
21,TKT-022,2024-03-11 09:03:00,High,Open,465.050000,AGT-11,API timeout errors in production
43,TKT-044,2024-02-08 12:13:00,High,Open,1229.883333,AGT-07,Request for account deletion
57,TKT-058,2024-03-01 08:47:00,High,Escalated,705.316667,AGT-09,Integration broken after version upgrade
...,...,...,...,...,...,...,...
474,TKT-475,2024-01-24 10:18:00,High,Open,1591.800000,AGT-02,Unexpected fee on account
478,TKT-479,2024-02-01 14:49:00,Critical,Open,1395.283333,AGT-08,Subscription not activated after payment
479,TKT-480,2024-01-13 16:42:00,High,Open,1849.400000,AGT-04,Data sync not working
487,TKT-488,2024-03-20 11:20:00,High,Escalated,246.766667,AGT-12,How to add team members
495,TKT-496,2024-02-11 13:26:00,Critical,Escalated,1156.666667,AGT-11,Question about usage limits

In [39]:
# Combine Anomaly Results

df["is_anomaly"] = False

df.loc[
    df["resolution_time_hrs"] > resolution_threshold,
    "is_anomaly"
] = True

df.loc[
    (df["priority"].isin(["High", "Critical"])) &
    (df["status"] != "Resolved") &
    (df["ticket_age_hrs"] > 24),
    "is_anomaly"
] = True

In [40]:
# Count Anomalies

df["is_anomaly"].sum()

np.int64(97)

In [41]:
# All Anomalies

anomalies = df[df["is_anomaly"] == True]

anomalies[
    [
        "ticket_id",
        "priority",
        "status",
        "resolution_time_hrs",
        "ticket_age_hrs",
        "agent_id",
        "issue_summary"
    ]
]

,ticket_id,priority,status,resolution_time_hrs,ticket_age_hrs,agent_id,issue_summary
6,TKT-007,High,Open,NaN,1658.700000,AGT-05,Question about usage limits
12,TKT-013,High,Open,NaN,608.183333,AGT-11,Question about usage limits
21,TKT-022,High,Open,NaN,465.050000,AGT-11,API timeout errors in production
22,TKT-023,Low,Resolved,76.1,650.883333,AGT-07,Payment failed but amount deducted
43,TKT-044,High,Open,NaN,1229.883333,AGT-07,Request for account deletion
...,...,...,...,...,...,...,...
474,TKT-475,High,Open,NaN,1591.800000,AGT-02,Unexpected fee on account
478,TKT-479,Critical,Open,NaN,1395.283333,AGT-08,Subscription not activated after payment
479,TKT-480,High,Open,NaN,1849.400000,AGT-04,Data sync not working
487,TKT-488,High,Escalated,NaN,246.766667,AGT-12,How to add team members
495,TKT-496,Critical,Escalated,NaN,1156.666667,AGT-11,Question about usage limits

In [44]:
# High-Priority Unresolved Query

def get_high_priority_unresolved():
    return df[
        (df["priority"].isin(["High", "Critical"])) &
        (df["status"] != "Resolved")
    ]

In [45]:
# Average Rating by Category

def get_average_rating_by_category(category):
    result = df[
        df["category"].str.lower() == category.lower()
    ]["customer_rating"].mean()

    return result

In [46]:
# Average Rating Query

def get_average_rating(category):
    return df[
        df["category"].str.lower() == category.lower()
    ]["customer_rating"].mean()

In [47]:
# Average Resolution Time

def get_average_resolution(category):
    return df[
        df["category"].str.lower() == category.lower()
    ]["resolution_time_hrs"].mean()

In [48]:
# Agent Resolution Count

def get_agent_resolution_count():
    return df[
        df["status"] == "Resolved"
    ]["agent_id"].value_counts()

In [49]:
# Long Resolution Query

def get_long_resolution_tickets():
    return df[
        df["resolution_time_hrs"] > resolution_threshold
    ]

In [50]:
# Old High-Priority Query

def get_old_high_priority():
    return df[
        (df["priority"].isin(["High", "Critical"])) &
        (df["status"] != "Resolved") &
        (df["ticket_age_hrs"] > 24)
    ]

In [51]:
# Anomaly Query

def get_anomalies():
    return df[df["is_anomaly"] == True]

In [53]:
# Open Tickets Query

def get_open_tickets():
    return (df["status"] == "Open").sum()

In [54]:
# Test Query Functions

print("Open tickets:", get_open_tickets())
print("High-priority unresolved:", len(get_high_priority_unresolved()))
print("Anomalies:", len(get_anomalies()))

Open tickets: 111
High-priority unresolved: 80
Anomalies: 97

In [55]:
# Category Ticket Count

def get_category_ticket_count(category):
    return (
        df["category"].str.lower() == category.lower()
    ).sum()

In [56]:
# Priority Ticket Count

def get_priority_ticket_count(priority):
    return (
        df["priority"].str.lower() == priority.lower()
    ).sum()

In [57]:
# Status Ticket Count

def get_status_ticket_count(status):
    return (
        df["status"].str.lower() == status.lower()
    ).sum()

In [58]:
# Test Basic Queries

print("Technical tickets:", get_category_ticket_count("Technical"))
print("Critical tickets:", get_priority_ticket_count("Critical"))
print("Open tickets:", get_status_ticket_count("Open"))

Technical tickets: 152
Critical tickets: 55
Open tickets: 111

In [59]:
# Tickets Resolved by Agent

def get_resolved_by_agent(agent_id):
    return df[
        (df["agent_id"].str.lower() == agent_id.lower()) &
        (df["status"] == "Resolved")
    ].shape[0]

In [60]:
# Top Resolving Agent

def get_top_resolving_agent():
    resolved = df[df["status"] == "Resolved"]
    return resolved["agent_id"].value_counts().idxmax()

In [61]:
# Test Agent Query

print("Top resolving agent:", get_top_resolving_agent())

Top resolving agent: AGT-09

In [62]:
# Current Anomaly Count

def get_anomaly_count():
    return df["is_anomaly"].sum()

In [63]:
# Test Anomaly Count

print("Total anomalies:", get_anomaly_count())

Total anomalies: 97

In [64]:
# Query Result Formatter

def format_number(value):
    if isinstance(value, (int, np.integer)):
        return str(value)
    
    if isinstance(value, (float, np.floating)):
        return f"{value:.2f}"
    
    return str(value)

In [65]:
# Simple Query Parser

def detect_query_type(question):
    question = question.lower()

    if "how many" in question and "open" in question:
        return "open_count"

    if "average" in question and "rating" in question:
        return "average_rating"

    if "anomal" in question:
        return "anomalies"

    if "resolved the most" in question or "most tickets" in question:
        return "top_agent"

    return "unknown"

In [66]:
# Query Executor

def execute_query(question):
    query_type = detect_query_type(question)

    if query_type == "open_count":
        return f"There are {get_open_tickets()} open tickets."

    elif query_type == "anomalies":
        return f"There are {get_anomaly_count()} detected anomalies."

    elif query_type == "top_agent":
        return f"The agent who resolved the most tickets is {get_top_resolving_agent()}."

    elif query_type == "average_rating":
        return "Please specify the category for the average rating."

    else:
        return "Sorry, I could not understand the query."

In [67]:
# Test Natural Language Queries

print(execute_query("How many tickets are currently open?"))
print(execute_query("Are there any anomalies in resolution times?"))
print(execute_query("Which agent resolved the most tickets?"))

There are 111 open tickets.
There are 97 detected anomalies.
The agent who resolved the most tickets is AGT-09.

In [68]:
# Extract Category

def extract_category(question):
    question_lower = question.lower()

    for category in df["category"].dropna().unique():
        if category.lower() in question_lower:
            return category

    return None

In [69]:
# Test Category Extraction

print(extract_category(
    "What is the average customer rating for Technical category tickets?"
))

Technical

In [70]:
# Improved Query Executor

def execute_query(question):
    query_type = detect_query_type(question)

    if query_type == "open_count":
        return f"There are {get_open_tickets()} open tickets."

    elif query_type == "anomalies":
        return f"There are {get_anomaly_count()} detected anomalies."

    elif query_type == "top_agent":
        return f"The agent who resolved the most tickets is {get_top_resolving_agent()}."

    elif query_type == "average_rating":
        category = extract_category(question)

        if category:
            rating = get_average_rating(category)
            return f"The average customer rating for {category} tickets is {rating:.2f}."

        return "Please specify the category for the average rating."

    else:
        return "Sorry, I could not understand the query."

In [71]:
# Test Improved Query

print(execute_query(
    "What is the average customer rating for Technical category tickets?"
))

The average customer rating for Technical tickets is 3.74.

In [72]:
# Critical Tickets Not Resolved Within 12 Hours

def get_critical_not_resolved_12h():
    return df[
        (df["priority"] == "Critical") &
        (df["status"] != "Resolved") &
        (
            df["response_time_hrs"].fillna(0) > 12
        )
    ]

In [73]:
# Test Critical 12-Hour Query

critical_12h = get_critical_not_resolved_12h()

print("Critical unresolved tickets over 12 hours:", len(critical_12h))

Critical unresolved tickets over 12 hours: 0

In [74]:
# Critical Tickets Not Resolved Within 12 Hours

def get_critical_not_resolved_12h():
    return df[
        (df["priority"] == "Critical") &
        (
            (df["status"] != "Resolved") |
            (df["resolution_time_hrs"] > 12)
        )
    ]

In [75]:
# Test Corrected Critical Query

critical_12h = get_critical_not_resolved_12h()

print("Critical tickets not resolved within 12 hours:", len(critical_12h))

Critical tickets not resolved within 12 hours: 34

In [76]:
# Show Critical 12-Hour Tickets

critical_12h[
    [
        "ticket_id",
        "created_at",
        "priority",
        "status",
        "response_time_hrs",
        "resolution_time_hrs",
        "agent_id",
        "issue_summary"
    ]
]

,ticket_id,created_at,priority,status,response_time_hrs,resolution_time_hrs,agent_id,issue_summary
59,TKT-060,2024-02-29 12:49:00,Critical,Escalated,1.0,NaN,AGT-06,How to export data to CSV
60,TKT-061,2024-01-14 17:01:00,Critical,Open,3.0,NaN,AGT-05,Wrong plan charged
63,TKT-064,2024-03-22 15:45:00,Critical,Escalated,2.3,NaN,AGT-03,Data sync not working
86,TKT-087,2024-03-23 10:31:00,Critical,Escalated,1.6,NaN,AGT-12,SSL certificate issue
87,TKT-088,2024-02-01 15:35:00,Critical,Open,2.0,NaN,AGT-03,Database connection timeout
90,TKT-091,2024-01-25 11:36:00,Critical,Escalated,1.3,NaN,AGT-07,System login failure after update
110,TKT-111,2024-03-23 13:03:00,Critical,Open,1.5,NaN,AGT-07,Change notification preferences
123,TKT-124,2024-03-29 12:01:00,Critical,Escalated,1.5,NaN,AGT-03,Request for account deletion
163,TKT-164,2024-02-05 18:50:00,Critical,Escalated,0.6,NaN,AGT-01,Request for account deletion
174,TKT-175,2024-03-07 12:54:00,Critical,Escalated,1.4,NaN,AGT-02,Database connection timeout
193,TKT-194,2024-02-13 16:22:00,Critical,Escalated,3.9,NaN,AGT-11,Data sync not working
216,TKT-217,2024-01-15 08:51:00,Critical,Escalated,2.2,NaN,AGT-11,Incorrect charge on invoice
225,TKT-226,2024-01-16 15:58:00,Critical,Escalated,3.5,NaN,AGT-04,Wrong plan charged
237,TKT-238,2024-01-30 11:57:00,Critical,Resolved,4.5,53.4,AGT-12,Request for product documentation
238,TKT-239,2024-02-10 08:13:00,Critical,Escalated,0.9,NaN,AGT-10,Wrong plan charged
254,TKT-255,2024-03-27 18:25:00,Critical,Resolved,4.8,66.6,AGT-06,Question about usage limits
271,TKT-272,2024-02-22 08:17:00,Critical,Open,0.8,NaN,AGT-11,Subscription not activated after payment
281,TKT-282,2024-01-19 09:33:00,Critical,Escalated,0.2,NaN,AGT-10,Change notification preferences
290,TKT-291,2024-01-20 16:20:00,Critical,Escalated,3.0,NaN,AGT-07,How to export data to CSV
309,TKT-310,2024-02-26 10:05:00,Critical,Open,0.8,NaN,AGT-06,Incorrect charge on invoice
321,TKT-322,2024-03-22 15:41:00,Critical,Open,1.0,NaN,AGT-06,Request for account deletion
324,TKT-325,2024-01-22 18:56:00,Critical,Escalated,4.1,NaN,AGT-02,Error 500 on checkout page
328,TKT-329,2024-01-12 13:38:00,Critical,Escalated,4.5,NaN,AGT-10,How to add team members
337,TKT-338,2024-01-25 10:02:00,Critical,Escalated,0.6,NaN,AGT-07,Subscription not activated after payment
351,TKT-352,2024-03-23 10:38:00,Critical,Escalated,1.3,NaN,AGT-01,Data sync not working
360,TKT-361,2024-01-10 15:56:00,Critical,Open,2.6,NaN,AGT-04,How to add team members
390,TKT-391,2024-03-29 11:17:00,Critical,Open,4.8,NaN,AGT-07,Webhook not triggering
398,TKT-399,2024-03-23 13:48:00,Critical,Escalated,2.8,NaN,AGT-10,Subscription not activated after payment
429,TKT-430,2024-03-22 08:56:00,Critical,Escalated,3.7,NaN,AGT-12,How to export data to CSV
445,TKT-446,2024-02-05 11:38:00,Critical,Resolved,2.4,60.6,AGT-04,Database connection timeout
452,TKT-453,2024-03-04 17:00:00,Critical,Escalated,4.8,NaN,AGT-09,Request for account deletion
462,TKT-463,2024-02-06 13:20:00,Critical,Escalated,2.7,NaN,AGT-11,Payment failed but amount deducted
478,TKT-479,2024-02-01 14:49:00,Critical,Open,1.4,NaN,AGT-08,Subscription not activated after payment
495,TKT-496,2024-02-11 13:26:00,Critical,Escalated,2.3,NaN,AGT-11,Question about usage limits

In [77]:
# Anomaly Summary

def get_anomaly_summary():
    anomalies = get_anomalies()

    return {
        "total_anomalies": len(anomalies),
        "long_resolution": len(get_long_resolution_tickets()),
        "old_high_priority": len(get_old_high_priority())
    }

In [78]:
# Test Anomaly Summary

print(get_anomaly_summary())

{'total_anomalies': 97, 'long_resolution': 17, 'old_high_priority': 80}

In [80]:
# Detect Priority

def extract_priority(question):
    question_lower = question.lower()

    for priority in df["priority"].dropna().unique():
        if priority.lower() in question_lower:
            return priority

    return None

In [81]:
# Detect Status

def extract_status(question):
    question_lower = question.lower()

    for status in df["status"].dropna().unique():
        if status.lower() in question_lower:
            return status

    return None

In [82]:
# Detect Filters

def extract_filters(question):
    return {
        "category": extract_category(question),
        "priority": extract_priority(question),
        "status": extract_status(question)
    }

In [84]:
# Test Filter Detection

print(extract_filters(
    "Show me all Critical Technical tickets that are Open."
))

{'category': 'Technical', 'priority': 'Critical', 'status': 'Open'}

In [85]:
# Apply Query Filters

def apply_filters(filters):
    result = df.copy()

    if filters["category"]:
        result = result[
            result["category"].str.lower() == filters["category"].lower()
        ]

    if filters["priority"]:
        result = result[
            result["priority"].str.lower() == filters["priority"].lower()
        ]

    if filters["status"]:
        result = result[
            result["status"].str.lower() == filters["status"].lower()
        ]

    return result

In [86]:
# Test Filter Application

filters = extract_filters(
    "Show me all Critical Technical tickets that are Open."
)

filtered_tickets = apply_filters(filters)

print("Matching tickets:", len(filtered_tickets))
filtered_tickets[
    ["ticket_id", "category", "priority", "status"]
]

Matching tickets: 2

    ticket_id   category  priority status
87    TKT-088  Technical  Critical   Open
390   TKT-391  Technical  Critical   Open

In [87]:
# General Filtered Ticket Query

def get_filtered_tickets(question):
    filters = extract_filters(question)
    return apply_filters(filters)

In [88]:
# Count Filtered Tickets

def count_filtered_tickets(question):
    return len(get_filtered_tickets(question))

In [89]:
# Test Count Query

print(
    count_filtered_tickets(
        "Show me all Critical Technical tickets that are Open."
    )
)

2

In [90]:
# Query Result Table

def get_query_table(question):
    result = get_filtered_tickets(question)

    columns = [
        "ticket_id",
        "category",
        "priority",
        "status",
        "agent_id",
        "issue_summary"
    ]

    return result[columns]

In [91]:
# Query Table Test

result = get_query_table(
    "Show me all Critical Technical tickets that are Open."
)

print("Matching tickets:", len(result))
result

Matching tickets: 2

,ticket_id,category,priority,status,agent_id,issue_summary
87,TKT-088,Technical,Critical,Open,AGT-03,Database connection timeout
390,TKT-391,Technical,Critical,Open,AGT-07,Webhook not triggering

In [92]:
# Natural Language Response

def answer_query(question):
    query_type = detect_query_type(question)

    if query_type == "open_count":
        return f"There are {get_open_tickets()} open tickets."

    elif query_type == "average_rating":
        category = extract_category(question)

        if category:
            rating = get_average_rating(category)
            return f"The average customer rating for {category} tickets is {rating:.2f}."

        return "Please specify the category."

    elif query_type == "anomalies":
        return f"There are {get_anomaly_count()} detected anomalies."

    elif query_type == "top_agent":
        agent = get_top_resolving_agent()
        return f"{agent} resolved the most tickets."

    return f"There are {count_filtered_tickets(question)} matching tickets."

In [94]:
# Test Main Query Function

questions = [
    "How many tickets are currently open?",
    "What is the average customer rating for Technical category tickets?",
    "Which agent resolved the most tickets?",
    "Are there any anomalies in resolution times?"
]

for question in questions:
    print("Question:", question)
    print("Answer:", answer_query(question))
    print()

Question: How many tickets are currently open?
Answer: There are 111 open tickets.

Question: What is the average customer rating for Technical category tickets?
Answer: The average customer rating for Technical tickets is 3.74.

Question: Which agent resolved the most tickets?
Answer: AGT-09 resolved the most tickets.

Question: Are there any anomalies in resolution times?
Answer: There are 97 detected anomalies.

In [95]:
# Query Result with Ticket Details

def answer_with_details(question):
    query_type = detect_query_type(question)

    if query_type == "open_count":
        return f"There are {get_open_tickets()} open tickets."

    elif query_type == "anomalies":
        return get_anomaly_summary()

    elif query_type == "top_agent":
        return f"The agent who resolved the most tickets is {get_top_resolving_agent()}."

    elif query_type == "average_rating":
        category = extract_category(question)

        if category:
            rating = get_average_rating(category)
            return f"The average customer rating for {category} tickets is {rating:.2f}."

        return "Please specify the category."

    else:
        return get_query_table(question)

In [96]:
# Test Detailed Query Response

print(answer_with_details(
    "How many tickets are currently open?"
))

print()

print(answer_with_details(
    "Are there any anomalies in resolution times?"
))

There are 111 open tickets.

{'total_anomalies': 97, 'long_resolution': 17, 'old_high_priority': 80}

In [97]:
# Detect Query Intent

def detect_query_intent(question):
    question = question.lower()

    if "how many" in question and "open" in question:
        return "open_count"

    if "average" in question and "rating" in question:
        return "average_rating"

    if "resolved the most" in question or "most tickets" in question:
        return "top_agent"

    if "anomal" in question:
        return "anomalies"

    if "critical" in question and "12 hours" in question:
        return "critical_12h"

    return "filtered_count"

In [98]:
# Execute Detected Intent

def execute_intent(question):
    intent = detect_query_intent(question)

    if intent == "open_count":
        return f"There are {get_open_tickets()} open tickets."

    elif intent == "average_rating":
        category = extract_category(question)

        if category:
            rating = get_average_rating(category)
            return f"The average customer rating for {category} tickets is {rating:.2f}."

        return "Please specify the category."

    elif intent == "top_agent":
        return f"The agent who resolved the most tickets is {get_top_resolving_agent()}."

    elif intent == "anomalies":
        return get_anomaly_summary()

    elif intent == "critical_12h":
        return get_critical_not_resolved_12h()

    else:
        return f"There are {count_filtered_tickets(question)} matching tickets."

In [99]:
# Test Intent Execution

test_questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets?",
    "Are there any anomalies in resolution times?",
    "Show me all Critical tickets not resolved within 12 hours."
]

for question in test_questions:
    print("Question:", question)
    print("Result:", execute_intent(question))
    print("-" * 50)

Question: How many tickets are currently open?
Result: There are 111 open tickets.
--------------------------------------------------
Question: Which agent resolved the most tickets?
Result: The agent who resolved the most tickets is AGT-09.
--------------------------------------------------
Question: Are there any anomalies in resolution times?
Result: {'total_anomalies': 97, 'long_resolution': 17, 'old_high_priority': 80}
--------------------------------------------------
Question: Show me all Critical tickets not resolved within 12 hours.
Result:     ticket_id          created_at   category  priority     status  \
59    TKT-060 2024-02-29 12:49:00    General  Critical  Escalated
60    TKT-061 2024-01-14 17:01:00    Billing  Critical       Open
63    TKT-064 2024-03-22 15:45:00  Technical  Critical  Escalated
86    TKT-087 2024-03-23 10:31:00  Technical  Critical  Escalated
87    TKT-088 2024-02-01 15:35:00  Technical  Critical       Open
90    TKT-091 2024-01-25 11:36:00  Technical  Critical  Escalated
110   TKT-111 2024-03-23 13:03:00    General  Critical       Open
123   TKT-124 2024-03-29 12:01:00    General  Critical  Escalated
163   TKT-164 2024-02-05 18:50:00    General  Critical  Escalated
174   TKT-175 2024-03-07 12:54:00  Technical  Critical  Escalated
193   TKT-194 2024-02-13 16:22:00  Technical  Critical  Escalated
216   TKT-217 2024-01-15 08:51:00    Billing  Critical  Escalated
225   TKT-226 2024-01-16 15:58:00    Billing  Critical  Escalated
237   TKT-238 2024-01-30 11:57:00    General  Critical   Resolved
238   TKT-239 2024-02-10 08:13:00    Billing  Critical  Escalated
254   TKT-255 2024-03-27 18:25:00    General  Critical   Resolved
271   TKT-272 2024-02-22 08:17:00    Billing  Critical       Open
281   TKT-282 2024-01-19 09:33:00    General  Critical  Escalated
290   TKT-291 2024-01-20 16:20:00    General  Critical  Escalated
309   TKT-310 2024-02-26 10:05:00    Billing  Critical       Open
321   TKT-322 2024-03-22 15:41:00    General  Critical       Open
324   TKT-325 2024-01-22 18:56:00  Technical  Critical  Escalated
328   TKT-329 2024-01-12 13:38:00    General  Critical  Escalated
337   TKT-338 2024-01-25 10:02:00    Billing  Critical  Escalated
351   TKT-352 2024-03-23 10:38:00  Technical  Critical  Escalated
360   TKT-361 2024-01-10 15:56:00    General  Critical       Open
390   TKT-391 2024-03-29 11:17:00  Technical  Critical       Open
398   TKT-399 2024-03-23 13:48:00    Billing  Critical  Escalated
429   TKT-430 2024-03-22 08:56:00    General  Critical  Escalated
445   TKT-446 2024-02-05 11:38:00  Technical  Critical   Resolved
452   TKT-453 2024-03-04 17:00:00    General  Critical  Escalated
462   TKT-463 2024-02-06 13:20:00    Billing  Critical  Escalated
478   TKT-479 2024-02-01 14:49:00    Billing  Critical       Open
495   TKT-496 2024-02-11 13:26:00    General  Critical  Escalated

     response_time_hrs  resolution_time_hrs agent_id  customer_rating  \
59                 1.0                  NaN   AGT-06              NaN
60                 3.0                  NaN   AGT-05              NaN
63                 2.3                  NaN   AGT-03              NaN
86                 1.6                  NaN   AGT-12              NaN
87                 2.0                  NaN   AGT-03              NaN
90                 1.3                  NaN   AGT-07              NaN
110                1.5                  NaN   AGT-07              NaN
123                1.5                  NaN   AGT-03              NaN
163                0.6                  NaN   AGT-01              NaN
174                1.4                  NaN   AGT-02              NaN
193                3.9                  NaN   AGT-11              NaN
216                2.2                  NaN   AGT-11              NaN
225                3.5                  NaN   AGT-04              NaN
237                4.5                 53.4   AGT-12              5.0
238                0.9                  NaN   AGT-10              NaN
254                4.8                 66.6   AGT-06              4.0
271                0.8                  NaN   AGT-11              NaN
281                0.2                  NaN   AGT-10              NaN
290                3.0                  NaN   AGT-07              NaN
309                0.8                  NaN   AGT-06              NaN
321                1.0                  NaN   AGT-06              NaN
324                4.1                  NaN   AGT-02              NaN
328                4.5                  NaN   AGT-10              NaN
337                0.6                  NaN   AGT-07              NaN
351                1.3                  NaN   AGT-01              NaN
360                2.6                  NaN   AGT-04              NaN
390                4.8                  NaN   AGT-07              NaN
398                2.8                  NaN   AGT-10              NaN
429                3.7                  NaN   AGT-12              NaN
445                2.4                 60.6   AGT-04              4.0
452                4.8                  NaN   AGT-09              NaN
462                2.7                  NaN   AGT-11              NaN
478                1.4                  NaN   AGT-08              NaN
495                2.3                  NaN   AGT-11              NaN

                                issue_summary  ticket_age_hrs  is_anomaly
59                  How to export data to CSV      725.283333        True
60                         Wrong plan charged     1825.083333        True
63                      Data sync not working      194.350000        True
86                      SSL certificate issue      175.583333        True
87                Database connection timeout     1394.516667        True
90          System login failure after update     1566.500000        True
110           Change notification preferences      173.050000        True
123              Request for account deletion       30.083333        True
163              Request for account deletion     1295.266667        True
174               Database connection timeout      557.200000        True
193                     Data sync not working     1105.733333        True
216               Incorrect charge on invoice     1809.250000        True
225                        Wrong plan charged     1778.133333        True
237         Request for product documentation     1446.150000       False
238                        Wrong plan charged     1185.883333        True
254               Question about usage limits       71.683333        True
271  Subscription not activated after payment      897.816667        True
281           Change notification preferences     1712.550000        True
290                 How to export data to CSV     1681.766667        True
309               Incorrect charge on invoice      800.016667        True
321              Request for account deletion      194.416667        True
324                Error 500 on checkout page     1631.166667        True
328                   How to add team members     1876.466667        True
337  Subscription not activated after payment     1568.066667        True
351                     Data sync not working      175.466667        True
360                   How to add team members     1922.166667        True
390                    Webhook not triggering       30.816667        True
398  Subscription not activated after payment      172.300000        True
429                 How to export data to CSV      201.166667        True
445               Database connection timeout     1302.466667        True
452              Request for account deletion      625.100000        True
462        Payment failed but amount deducted     1276.766667        True
478  Subscription not activated after payment     1395.283333        True
495               Question about usage limits     1156.666667        True
--------------------------------------------------

In [100]:
# Format Critical Ticket Results

def format_ticket_results(tickets):
    if len(tickets) == 0:
        return "No matching tickets found."

    return tickets[
        [
            "ticket_id",
            "priority",
            "status",
            "resolution_time_hrs",
            "agent_id"
        ]
    ].to_string(index=False)

In [101]:
# Final Query Response Formatter

def final_query_response(question):
    intent = detect_query_intent(question)

    if intent == "open_count":
        return f"There are {get_open_tickets()} open tickets."

    elif intent == "average_rating":
        category = extract_category(question)

        if category:
            rating = get_average_rating(category)
            return f"The average customer rating for {category} tickets is {rating:.2f}."

        return "Please specify the category."

    elif intent == "top_agent":
        return f"The agent who resolved the most tickets is {get_top_resolving_agent()}."

    elif intent == "anomalies":
        return get_anomaly_summary()

    elif intent == "critical_12h":
        tickets = get_critical_not_resolved_12h()
        return format_ticket_results(tickets)

    else:
        tickets = get_filtered_tickets(question)
        return format_ticket_results(tickets)

In [102]:
# Test Final Query Function

questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets?",
    "What is the average customer rating for Technical category tickets?",
    "Are there any anomalies in resolution times?",
    "Show me all Critical tickets not resolved within 12 hours."
]

for question in questions:
    print("Question:", question)
    print(final_query_response(question))
    print("=" * 60)

Question: How many tickets are currently open?
There are 111 open tickets.
============================================================
Question: Which agent resolved the most tickets?
The agent who resolved the most tickets is AGT-09.
============================================================
Question: What is the average customer rating for Technical category tickets?
The average customer rating for Technical tickets is 3.74.
============================================================
Question: Are there any anomalies in resolution times?
{'total_anomalies': 97, 'long_resolution': 17, 'old_high_priority': 80}
============================================================
Question: Show me all Critical tickets not resolved within 12 hours.
ticket_id priority    status  resolution_time_hrs agent_id
  TKT-060 Critical Escalated                  NaN   AGT-06
  TKT-061 Critical      Open                  NaN   AGT-05
  TKT-064 Critical Escalated                  NaN   AGT-03
  TKT-087 Critical Escalated                  NaN   AGT-12
  TKT-088 Critical      Open                  NaN   AGT-03
  TKT-091 Critical Escalated                  NaN   AGT-07
  TKT-111 Critical      Open                  NaN   AGT-07
  TKT-124 Critical Escalated                  NaN   AGT-03
  TKT-164 Critical Escalated                  NaN   AGT-01
  TKT-175 Critical Escalated                  NaN   AGT-02
  TKT-194 Critical Escalated                  NaN   AGT-11
  TKT-217 Critical Escalated                  NaN   AGT-11
  TKT-226 Critical Escalated                  NaN   AGT-04
  TKT-238 Critical  Resolved                 53.4   AGT-12
  TKT-239 Critical Escalated                  NaN   AGT-10
  TKT-255 Critical  Resolved                 66.6   AGT-06
  TKT-272 Critical      Open                  NaN   AGT-11
  TKT-282 Critical Escalated                  NaN   AGT-10
  TKT-291 Critical Escalated                  NaN   AGT-07
  TKT-310 Critical      Open                  NaN   AGT-06
  TKT-322 Critical      Open                  NaN   AGT-06
  TKT-325 Critical Escalated                  NaN   AGT-02
  TKT-329 Critical Escalated                  NaN   AGT-10
  TKT-338 Critical Escalated                  NaN   AGT-07
  TKT-352 Critical Escalated                  NaN   AGT-01
  TKT-361 Critical      Open                  NaN   AGT-04
  TKT-391 Critical      Open                  NaN   AGT-07
  TKT-399 Critical Escalated                  NaN   AGT-10
  TKT-430 Critical Escalated                  NaN   AGT-12
  TKT-446 Critical  Resolved                 60.6   AGT-04
  TKT-453 Critical Escalated                  NaN   AGT-09
  TKT-463 Critical Escalated                  NaN   AGT-11
  TKT-479 Critical      Open                  NaN   AGT-08
  TKT-496 Critical Escalated                  NaN   AGT-11
============================================================

In [104]:
# Install Groq

%pip install groq

Collecting groq
  Downloading groq-1.7.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in c:\users\rashn\anaconda3\lib\site-packages (from groq) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\rashn\anaconda3\lib\site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\rashn\anaconda3\lib\site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in c:\users\rashn\anaconda3\lib\site-packages (from groq) (2.13.5)
Requirement already satisfied: sniffio in c:\users\rashn\anaconda3\lib\site-packages (from groq) (1.3.0)
Requirement already satisfied: typing-extensions<5,>=4.14 in c:\users\rashn\anaconda3\lib\site-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in c:\users\rashn\anaconda3\lib\site-packages (from anyio<5,>=3.5.0->groq) (3.19)
Requirement already satisfied: certifi in c:\users\rashn\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->groq) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\rashn\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\rashn\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\rashn\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\rashn\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->groq) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\rashn\anaconda3\lib\site-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-1.7.0-py3-none-any.whl (143 kB)
Installing collected packages: groq
Successfully installed groq-1.7.0
Note: you may need to restart the kernel to use updated packages.

In [105]:
# Import Groq

from groq import Groq

In [106]:
# Groq API Key

import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("Enter your Groq API key: ")

print("Groq API key loaded successfully.")

Enter your Groq API key:  ········

Groq API key loaded successfully.

In [107]:
# Groq Connection Test

from groq import Groq
import os

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

models = client.models.list()

print("Groq connected successfully!")
print("Available models:")

for model in models.data[:10]:
    print("-", model.id)

Groq connected successfully!
Available models:
- openai/gpt-oss-safeguard-20b
- groq/compound-mini
- meta-llama/llama-prompt-guard-2-22m
- whisper-large-v3-turbo
- groq/compound
- openai/gpt-oss-120b
- qwen/qwen3.8-27b
- canopylabs/orpheus-v1-english
- openai/gpt-oss-20b
- canopylabs/orpheus-arabic-saudi

In [108]:
# Select Groq Model

preferred_models = [
    "llama-3.3-70b-versatile",
    "openai/gpt-oss-20b",
    "openai/gpt-oss-120b"
]

available_models = [model.id for model in models.data]

selected_model = None

for model_name in preferred_models:
    if model_name in available_models:
        selected_model = model_name
        break

if selected_model is None:
    selected_model = available_models[0]

print("Selected model:", selected_model)

Selected model: openai/gpt-oss-20b

In [109]:
# Test LLM Response

response = client.chat.completions.create(
    model=selected_model,
    messages=[
        {
            "role": "system",
            "content": "You are an AI assistant for a customer support ticket analytics system."
        },
        {
            "role": "user",
            "content": "Give a short greeting."
        }
    ],
    temperature=0
)

print(response.choices[0].message.content)

Hello! How can I help you today?

In [110]:
# LLM Query Function

def ask_groq(user_query):
    response = client.chat.completions.create(
        model=selected_model,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an AI assistant for a customer support ticket analytics system. "
                    "Understand the user's question clearly and provide a concise response. "
                    "Do not invent ticket numbers or statistics."
                )
            },
            {
                "role": "user",
                "content": user_query
            }
        ],
        temperature=0
    )
    
    return response.choices[0].message.content

In [111]:
# Test Groq With Project Query

test_question = "How many tickets are currently open?"

llm_answer = ask_groq(test_question)

print("Question:", test_question)
print("LLM Response:", llm_answer)

Question: How many tickets are currently open?
LLM Response: I don’t have real‑time access to the ticket system, so I can’t tell you the current number of open tickets. If you can share the relevant dashboard or export, I can help interpret it.

In [112]:
# LLM Data Query

def ask_data_question(user_query):
    data_result = execute_query(user_query)
    
    prompt = f"""
You are a customer support ticket analytics assistant.

User question:
{user_query}

Actual result calculated from the ticket dataset:
{data_result}

Answer the user's question using ONLY the actual result above.
Do not invent numbers or information.
Keep the answer concise and clear.
"""
    
    response = client.chat.completions.create(
        model=selected_model,
        messages=[
            {
                "role": "system",
                "content": "You answer customer support analytics questions using provided dataset results."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )
    
    return response.choices[0].message.content

In [113]:
# Test Data + LLM Answer

question = "How many tickets are currently open?"

answer = ask_data_question(question)

print("Question:", question)
print("Answer:", answer)

Question: How many tickets are currently open?
Answer: There are 111 open tickets.

In [114]:
# Test Multiple Natural-Language Queries

questions = [
    "How many tickets are currently open?",
    "What is the average customer rating for Technical category tickets?",
    "Are there any anomalies in resolution times?"
]

for question in questions:
    print("\nQuestion:", question)
    print("Answer:", ask_data_question(question))

Question: How many tickets are currently open?
Answer: There are 111 open tickets.

Question: What is the average customer rating for Technical category tickets?
Answer: The average customer rating for Technical category tickets is 3.74.

Question: Are there any anomalies in resolution times?
Answer: Yes—there are 97 detected anomalies in resolution times.

In [115]:
# Improve LLM Output Format

def ask_data_question(user_query):
    data_result = execute_query(user_query)
    
    prompt = f"""
You are a customer support ticket analytics assistant.

User question:
{user_query}

Actual result calculated from the dataset:
{data_result}

Instructions:
- Answer using ONLY the actual result provided.
- Do not invent or change numbers.
- Give a direct answer first.
- If the result is a list or table, summarize it clearly.
- Keep the response short and professional.
"""

    response = client.chat.completions.create(
        model=selected_model,
        messages=[
            {
                "role": "system",
                "content": "You answer customer support analytics questions accurately using dataset results."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )
    
    return response.choices[0].message.content

In [116]:
# Final AI Query Function

def ai_query(user_query):
    try:
        answer = ask_data_question(user_query)
        
        return {
            "question": user_query,
            "answer": answer,
            "status": "success"
        }
    
    except Exception as e:
        return {
            "question": user_query,
            "answer": "Unable to process the query.",
            "status": "error",
            "error": str(e)
        }

In [117]:
# Test Final AI Query

result = ai_query("How many tickets are currently open?")

print(result["question"])
print(result["answer"])
print(result["status"])

How many tickets are currently open?
There are 111 open tickets.
success

In [118]:
# LLM Intent Detection

def detect_llm_intent(user_query):
    prompt = f"""
Classify this customer support analytics question into exactly ONE intent:

- count
- agent
- anomaly
- filtered_tickets
- average_rating
- unknown

User question:
{user_query}

Return ONLY the intent name.
"""

    response = client.chat.completions.create(
        model=selected_model,
        messages=[
            {
                "role": "system",
                "content": "You classify customer support analytics questions."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip().lower()

In [119]:
# Test LLM Intent Detection

test_questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets?",
    "Are there any anomalies in resolution times?",
    "Show me all Critical tickets not resolved within 12 hours.",
    "What is the average customer rating for Technical category tickets?"
]

for question in test_questions:
    print("Question:", question)
    print("Intent:", detect_llm_intent(question))
    print("-" * 50)

Question: How many tickets are currently open?
Intent: count
--------------------------------------------------
Question: Which agent resolved the most tickets?
Intent: agent
--------------------------------------------------
Question: Are there any anomalies in resolution times?
Intent: anomaly
--------------------------------------------------
Question: Show me all Critical tickets not resolved within 12 hours.
Intent: filtered_tickets
--------------------------------------------------
Question: What is the average customer rating for Technical category tickets?
Intent: average_rating
--------------------------------------------------

In [120]:
# Connect LLM Intent to Query Engine

def llm_query(user_query):
    intent = detect_llm_intent(user_query)

    if intent == "count":
        result = execute_query(user_query)

    elif intent == "agent":
        result = execute_query(user_query)

    elif intent == "anomaly":
        result = execute_query(user_query)

    elif intent == "filtered_tickets":
        result = execute_query(user_query)

    elif intent == "average_rating":
        result = execute_query(user_query)

    else:
        result = "I could not understand the query."

    return {
        "intent": intent,
        "result": result
    }

In [121]:
# Test Complete LLM Query Flow

question = "How many tickets are currently open?"

result = llm_query(question)

print("Question:", question)
print("Intent:", result["intent"])
print("Result:", result["result"])

Question: How many tickets are currently open?
Intent: count
Result: There are 111 open tickets.

In [122]:
# Test All Main Query Types

questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets?",
    "Are there any anomalies in resolution times?",
    "Show me all Critical tickets not resolved within 12 hours.",
    "What is the average customer rating for Technical category tickets?"
]

for question in questions:
    result = llm_query(question)

    print("Question:", question)
    print("Intent:", result["intent"])
    print("Result:", result["result"])
    print("=" * 70)

Question: How many tickets are currently open?
Intent: count
Result: There are 111 open tickets.
======================================================================
Question: Which agent resolved the most tickets?
Intent: agent
Result: The agent who resolved the most tickets is AGT-09.
======================================================================
Question: Are there any anomalies in resolution times?
Intent: anomaly
Result: There are 97 detected anomalies.
======================================================================
Question: Show me all Critical tickets not resolved within 12 hours.
Intent: filtered_tickets
Result: Sorry, I could not understand the query.
======================================================================
Question: What is the average customer rating for Technical category tickets?
Intent: average_rating
Result: The average customer rating for Technical tickets is 3.74.
======================================================================

In [123]:
# Final Query Response

def final_ai_response(user_query):
    result = llm_query(user_query)

    if result["intent"] == "unknown":
        return "Sorry, I could not understand your question."

    data_result = result["result"]

    prompt = f"""
User question:
{user_query}

Intent:
{result["intent"]}

Actual dataset result:
{data_result}

Give a concise, professional answer.
Use ONLY the actual dataset result.
Do not invent any numbers or facts.
"""

    response = client.chat.completions.create(
        model=selected_model,
        messages=[
            {
                "role": "system",
                "content": "You are a customer support analytics assistant."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()

In [124]:
# Test Final AI Response

questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets?",
    "Are there any anomalies in resolution times?"
]

for question in questions:
    print("Question:", question)
    print("Answer:", final_ai_response(question))
    print("-" * 60)

Question: How many tickets are currently open?
Answer: There are 111 open tickets.
------------------------------------------------------------
Question: Which agent resolved the most tickets?
Answer: The agent who resolved the most tickets is AGT-09.
------------------------------------------------------------
Question: Are there any anomalies in resolution times?
Answer: There are 97 detected anomalies.
------------------------------------------------------------

In [125]:
# Create data_loader.py

data_loader_code = '''
import pandas as pd


def load_data(file_path="support_tickets.csv"):
    df = pd.read_csv(file_path)
    df["created_at"] = pd.to_datetime(df["created_at"])
    return df
'''

with open("data_loader.py", "w", encoding="utf-8") as file:
    file.write(data_loader_code)

print("data_loader.py created successfully!")

data_loader.py created successfully!

In [126]:
# Create anomaly_detector.py

anomaly_code = '''
import pandas as pd


def detect_anomalies(df):
    df = df.copy()

    resolution_threshold = df["resolution_time_hrs"].quantile(0.95)

    df["ticket_age_hrs"] = (
        df["created_at"].max() - df["created_at"]
    ).dt.total_seconds() / 3600

    df["is_anomaly"] = (
        (df["resolution_time_hrs"] > resolution_threshold)
        |
        (
            df["priority"].isin(["High", "Critical"])
            & (df["status"] != "Resolved")
            & (df["ticket_age_hrs"] > 24)
        )
    )

    return df[df["is_anomaly"]].copy()


def get_anomaly_summary(df):
    anomalies = detect_anomalies(df)

    return {
        "anomaly_count": len(anomalies),
        "resolution_threshold_95": round(
            df["resolution_time_hrs"].quantile(0.95), 2
        )
    }
'''

with open("anomaly_detector.py", "w", encoding="utf-8") as file:
    file.write(anomaly_code)

print("anomaly_detector.py created successfully!")

anomaly_detector.py created successfully!

In [127]:
# Create llm_handler.py

llm_handler_code = '''
import os
from groq import Groq


client = Groq(api_key=os.getenv("GROQ_API_KEY"))

MODEL_NAME = os.getenv(
    "GROQ_MODEL",
    "llama-3.3-70b-versatile"
)


def ask_llm(user_query, data_result):
    prompt = f"""
You are a customer support ticket analytics assistant.

User question:
{user_query}

Actual result calculated from the ticket dataset:
{data_result}

Instructions:
- Answer using ONLY the actual result provided.
- Do not invent or change numbers.
- Give a direct and concise answer.
- Keep the response professional.
"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": "You answer customer support analytics questions using provided dataset results."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()


def detect_intent(user_query):
    prompt = f"""
Classify this customer support analytics question into exactly ONE intent:

- count
- agent
- anomaly
- filtered_tickets
- average_rating
- unknown

User question:
{user_query}

Return ONLY the intent name.
"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": "You classify customer support analytics questions."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip().lower()
'''

with open("llm_handler.py", "w", encoding="utf-8") as file:
    file.write(llm_handler_code)

print("llm_handler.py created successfully!")

llm_handler.py created successfully!

In [128]:
# Create main.py

main_code = '''
from data_loader import load_data
from anomaly_detector import detect_anomalies, get_anomaly_summary
from llm_handler import ask_llm, detect_intent


df = load_data()


def get_open_tickets():
    return int((df["status"] == "Open").sum())


def get_anomaly_data():
    return detect_anomalies(df)


def get_average_rating(category=None):
    data = df.copy()

    if category:
        data = data[data["category"].str.lower() == category.lower()]

    return round(float(data["customer_rating"].mean()), 2)


def get_top_resolving_agent():
    resolved = df[df["status"] == "Resolved"]

    result = (
        resolved.groupby("agent_id")
        .size()
        .sort_values(ascending=False)
    )

    if result.empty:
        return None

    return {
        "agent_id": result.index[0],
        "resolved_tickets": int(result.iloc[0])
    }


def get_critical_not_resolved_12h():
    data = df.copy()

    data["ticket_age_hrs"] = (
        df["created_at"].max() - df["created_at"]
    ).dt.total_seconds() / 3600

    result = data[
        (data["priority"] == "Critical") &
        (
            (data["status"] != "Resolved") &
            (data["ticket_age_hrs"] > 12)
            |
            (data["status"] == "Resolved") &
            (data["resolution_time_hrs"] > 12)
        )
    ]

    return result


def execute_query(user_query):
    intent = detect_intent(user_query)

    query_lower = user_query.lower()

    if intent == "count":
        if "open" in query_lower:
            return get_open_tickets()

        if "critical" in query_lower:
            return len(get_critical_not_resolved_12h())

        return len(df)

    elif intent == "agent":
        return get_top_resolving_agent()

    elif intent == "anomaly":
        return get_anomaly_summary(df)

    elif intent == "average_rating":
        category = None

        for cat in df["category"].unique():
            if cat.lower() in query_lower:
                category = cat
                break

        return get_average_rating(category)

    elif intent == "filtered_tickets":
        if "critical" in query_lower and "12" in query_lower:
            result = get_critical_not_resolved_12h()

            return result[
                [
                    "ticket_id",
                    "priority",
                    "status",
                    "created_at",
                    "resolution_time_hrs"
                ]
            ].to_dict(orient="records")

        return []

    return "I could not understand the query."


def answer_query(user_query):
    data_result = execute_query(user_query)

    answer = ask_llm(user_query, data_result)

    return {
        "question": user_query,
        "intent": detect_intent(user_query),
        "data": data_result,
        "answer": answer
    }
'''

with open("main.py", "w", encoding="utf-8") as file:
    file.write(main_code)

print("main.py created successfully!")

main.py created successfully!

In [129]:
# Create app.py

app_code = '''
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from main import answer_query, get_anomaly_data


app = FastAPI(
    title="AI Support Ticket Analytics",
    description="AI-powered customer support ticket analytics system",
    version="1.0.0"
)


class QueryRequest(BaseModel):
    question: str


@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "AI Support Ticket Analytics"
    }


@app.post("/query")
def query_tickets(request: QueryRequest):
    return answer_query(request.question)


@app.get("/anomalies")
def anomalies():
    data = get_anomaly_data()

    return {
        "anomaly_count": len(data),
        "anomalies": data[
            [
                "ticket_id",
                "priority",
                "status",
                "resolution_time_hrs"
            ]
        ].to_dict(orient="records")
    }


@app.get("/", response_class=HTMLResponse)
def home():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>AI Support Ticket Analytics</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 900px;
                margin: 40px auto;
                padding: 20px;
            }

            input {
                width: 75%;
                padding: 12px;
                font-size: 16px;
            }

            button {
                padding: 12px 20px;
                font-size: 16px;
                cursor: pointer;
            }

            #result {
                margin-top: 25px;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 8px;
                white-space: pre-wrap;
            }
        </style>
    </head>

    <body>
        <h1>AI Support Ticket Analytics</h1>

        <p>Ask a question about the support tickets:</p>

        <input
            id="question"
            placeholder="How many tickets are currently open?"
        />

        <button onclick="askQuestion()">Ask</button>

        <div id="result">Answer will appear here...</div>

        <script>
            async function askQuestion() {
                const question = document.getElementById("question").value;

                if (!question) {
                    document.getElementById("result").innerText =
                        "Please enter a question.";
                    return;
                }

                document.getElementById("result").innerText =
                    "Processing...";

                const response = await fetch("/query", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        question: question
                    })
                });

                const data = await response.json();

                document.getElementById("result").innerText =
                    data.answer || JSON.stringify(data, null, 2);
            }
        </script>
    </body>
    </html>
    """
'''

with open("app.py", "w", encoding="utf-8") as file:
    file.write(app_code)

print("app.py created successfully!")

app.py created successfully!

In [130]:
# Create requirements.txt

requirements = """pandas
numpy
fastapi
uvicorn
pydantic
groq
python-dotenv
"""

with open("requirements.txt", "w", encoding="utf-8") as file:
    file.write(requirements)

print("requirements.txt created successfully!")

requirements.txt created successfully!

In [131]:
# Create requirements.txt

requirements = """pandas
numpy
fastapi
uvicorn
pydantic
groq
python-dotenv
"""

with open("requirements.txt", "w", encoding="utf-8") as file:
    file.write(requirements)

print("requirements.txt created successfully!")

requirements.txt created successfully!

In [132]:
# Load Environment Variables

from dotenv import load_dotenv
import os

load_dotenv()

print("GROQ API key loaded:", bool(os.getenv("GROQ_API_KEY")))
print("Groq model:", os.getenv("GROQ_MODEL"))

GROQ API key loaded: True
Groq model: None

In [133]:
# Fix Groq Model

import os

os.environ["GROQ_MODEL"] = selected_model

print("Groq model set successfully:", os.environ["GROQ_MODEL"])

Groq model set successfully: openai/gpt-oss-20b

In [136]:
# Test Final Project Backend

from main import answer_query

test = answer_query("How many tickets are currently open?")

print("Question:", test["question"])
print("Intent:", test["intent"])
print("Data:", test["data"])
print("AI Answer:", test["answer"])

Question: How many tickets are currently open?
Intent: count
Data: 111
AI Answer: 111

In [137]:
# Test All Backend Queries

questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets?",
    "Are there any anomalies in resolution times?",
    "What is the average customer rating for Technical category tickets?",
    "Show me all Critical tickets not resolved within 12 hours."
]

for question in questions:
    print("\nQuestion:", question)

    result = answer_query(question)

    print("Intent:", result["intent"])
    print("Data:", result["data"])
    print("AI Answer:", result["answer"])
    print("-" * 70)

Question: How many tickets are currently open?
Intent: count
Data: 111
AI Answer: 111
----------------------------------------------------------------------

Question: Which agent resolved the most tickets?
Intent: agent
Data: {'agent_id': 'AGT-09', 'resolved_tickets': 37}
AI Answer: Agent **AGT-09** resolved the most tickets, with **37** tickets.
----------------------------------------------------------------------

Question: Are there any anomalies in resolution times?
Intent: anomaly
Data: {'anomaly_count': 97, 'resolution_threshold_95': np.float64(60.12)}
AI Answer: Yes. The analysis identified **97 anomalies** in resolution times, with the 95th‑percentile threshold set at **60.12 minutes**.
----------------------------------------------------------------------

Question: What is the average customer rating for Technical category tickets?
Intent: average_rating
Data: 3.74
AI Answer: The average customer rating for Technical category tickets is **3.74**.
----------------------------------------------------------------------

Question: Show me all Critical tickets not resolved within 12 hours.
Intent: filtered_tickets
Data: [{'ticket_id': 'TKT-060', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-02-29 12:49:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-061', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-01-14 17:01:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-064', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-22 15:45:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-087', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-23 10:31:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-088', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-02-01 15:35:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-091', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-25 11:36:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-111', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-03-23 13:03:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-124', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-29 12:01:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-164', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-02-05 18:50:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-175', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-07 12:54:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-194', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-02-13 16:22:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-217', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-15 08:51:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-226', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-16 15:58:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-238', 'priority': 'Critical', 'status': 'Resolved', 'created_at': Timestamp('2024-01-30 11:57:00'), 'resolution_time_hrs': 53.4}, {'ticket_id': 'TKT-239', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-02-10 08:13:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-255', 'priority': 'Critical', 'status': 'Resolved', 'created_at': Timestamp('2024-03-27 18:25:00'), 'resolution_time_hrs': 66.6}, {'ticket_id': 'TKT-272', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-02-22 08:17:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-282', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-19 09:33:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-291', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-20 16:20:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-310', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-02-26 10:05:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-322', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-03-22 15:41:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-325', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-22 18:56:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-329', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-12 13:38:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-338', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-01-25 10:02:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-352', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-23 10:38:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-361', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-01-10 15:56:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-391', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-03-29 11:17:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-399', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-23 13:48:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-430', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-22 08:56:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-446', 'priority': 'Critical', 'status': 'Resolved', 'created_at': Timestamp('2024-02-05 11:38:00'), 'resolution_time_hrs': 60.6}, {'ticket_id': 'TKT-453', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-03-04 17:00:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-463', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-02-06 13:20:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-479', 'priority': 'Critical', 'status': 'Open', 'created_at': Timestamp('2024-02-01 14:49:00'), 'resolution_time_hrs': nan}, {'ticket_id': 'TKT-496', 'priority': 'Critical', 'status': 'Escalated', 'created_at': Timestamp('2024-02-11 13:26:00'), 'resolution_time_hrs': nan}]
AI Answer: **Critical tickets not resolved within 12 hours**

| Ticket ID | Priority | Status     | Created At           | Resolution Time (hrs) |
|-----------|----------|------------|----------------------|-----------------------|
| TKT-060   | Critical | Escalated  | 2024‑02‑29 12:49:00  | NaN                   |
| TKT-061   | Critical | Open       | 2024‑01‑14 17:01:00  | NaN                   |
| TKT-064   | Critical | Escalated  | 2024‑03‑22 15:45:00  | NaN                   |
| TKT-087   | Critical | Escalated  | 2024‑03‑23 10:31:00  | NaN                   |
| TKT-088   | Critical | Open       | 2024‑02‑01 15:35:00  | NaN                   |
| TKT-091   | Critical | Escalated  | 2024‑01‑25 11:36:00  | NaN                   |
| TKT-111   | Critical | Open       | 2024‑03‑23 13:03:00  | NaN                   |
| TKT-124   | Critical | Escalated  | 2024‑03‑29 12:01:00  | NaN                   |
| TKT-164   | Critical | Escalated  | 2024‑02‑05 18:50:00  | NaN                   |
| TKT-175   | Critical | Escalated  | 2024‑03‑07 12:54:00  | NaN                   |
| TKT-194   | Critical | Escalated  | 2024‑02‑13 16:22:00  | NaN                   |
| TKT-217   | Critical | Escalated  | 2024‑01‑15 08:51:00  | NaN                   |
| TKT-226   | Critical | Escalated  | 2024‑01‑16 15:58:00  | NaN                   |
| TKT-238   | Critical | Resolved   | 2024‑01‑30 11:57:00  | 53.4                  |
| TKT-239   | Critical | Escalated  | 2024‑02‑10 08:13:00  | NaN                   |
| TKT-255   | Critical | Resolved   | 2024‑03‑27 18:25:00  | 66.6                  |
| TKT-272   | Critical | Open       | 2024‑02‑22 08:17:00  | NaN                   |
| TKT-282   | Critical | Escalated  | 2024‑01‑19 09:33:00  | NaN                   |
| TKT-291   | Critical | Escalated  | 2024‑01‑20 16:20:00  | NaN                   |
| TKT-310   | Critical | Open       | 2024‑02‑26 10:05:00  | NaN                   |
| TKT-322   | Critical | Open       | 2024‑03‑22 15:41:00  | NaN                   |
| TKT-325   | Critical | Escalated  | 2024‑01‑22 18:56:00  | NaN                   |
| TKT-329   | Critical | Escalated  | 2024‑01‑12 13:38:00  | NaN                   |
| TKT-338   | Critical | Escalated  | 2024‑01‑25 10:02:00  | NaN                   |
| TKT-352   | Critical | Escalated  | 2024‑03‑23 10:38:00  | NaN                   |
| TKT-361   | Critical | Open       | 2024‑01‑10 15:56:00  | NaN                   |
| TKT-391   | Critical | Open       | 2024‑03‑29 11:17:00  | NaN                   |
| TKT-399   | Critical | Escalated  | 2024‑03‑23 13:48:00  | NaN                   |
| TKT-430   | Critical | Escalated  | 2024‑03‑22 08:56:00  | NaN                   |
| TKT-446   | Critical | Resolved   | 2024‑02‑05 11:38:00  | 60.6                  |
| TKT-453   | Critical | Escalated  | 2024‑03‑04 17:00:00  | NaN                   |
| TKT-463   | Critical | Escalated  | 2024‑02‑06 13:20:00  | NaN                   |
| TKT-479   | Critical | Open       | 2024‑02‑01 14:49:00  | NaN                   |
| TKT-496   | Critical | Escalated  | 2024‑02‑11 13:26:00  | NaN                   |

All listed tickets are either unresolved (NaN) or resolved after more than 12 hours.
----------------------------------------------------------------------

In [138]:
# Fix llm_handler.py Environment Loading

llm_handler_code = '''
import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

MODEL_NAME = os.getenv("GROQ_MODEL")

if not MODEL_NAME:
    MODEL_NAME = "llama-3.3-70b-versatile"


def ask_llm(user_query, data_result):
    prompt = f"""
You are a customer support ticket analytics assistant.

User question:
{user_query}

Actual result calculated from the customer support ticket dataset:
{data_result}

Instructions:
- Answer using ONLY the actual result provided.
- Do not invent or change numbers.
- Give a direct and concise answer.
- Keep the response professional.
"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": "You answer customer support analytics questions using provided dataset results."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip()


def detect_intent(user_query):
    prompt = f"""
Classify this customer support analytics question into exactly ONE intent:

- count
- agent
- anomaly
- filtered_tickets
- average_rating
- unknown

User question:
{user_query}

Return ONLY the intent name.
"""

    response = client.chat.completions.create(
        model=MODEL_NAME,
        messages=[
            {
                "role": "system",
                "content": "You classify customer support analytics questions."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    return response.choices[0].message.content.strip().lower()
'''

with open("llm_handler.py", "w", encoding="utf-8") as file:
    file.write(llm_handler_code)

print("llm_handler.py updated successfully!")

llm_handler.py updated successfully!

In [140]:
# Install Project Packages

%pip install fastapi uvicorn pydantic python-dotenv

Collecting fastapi
  Downloading fastapi-0.141.1-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn
  Downloading uvicorn-0.53.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: pydantic in c:\users\rashn\anaconda3\lib\site-packages (2.13.5)
Requirement already satisfied: python-dotenv in c:\users\rashn\anaconda3\lib\site-packages (1.1.0)
Collecting starlette>=0.46.0 (from fastapi)
  Downloading starlette-1.6.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\rashn\anaconda3\lib\site-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\rashn\anaconda3\lib\site-packages (from fastapi) (0.4.2)
Collecting annotated-doc>=0.0.2 (from fastapi)
  Downloading annotated_doc-0.0.5-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: click>=7.0 in c:\users\rashn\anaconda3\lib\site-packages (from uvicorn) (8.4.2)
Requirement already satisfied: h11>=0.8 in c:\users\rashn\anaconda3\lib\site-packages (from uvicorn) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\rashn\anaconda3\lib\site-packages (from pydantic) (0.6.0)
Requirement already satisfied: pydantic-core==2.46.5 in c:\users\rashn\anaconda3\lib\site-packages (from pydantic) (2.46.5)
Requirement already satisfied: colorama in c:\users\rashn\anaconda3\lib\site-packages (from click>=7.0->uvicorn) (0.4.6)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\rashn\anaconda3\lib\site-packages (from starlette>=0.46.0->fastapi) (4.10.0)
Requirement already satisfied: idna>=2.8 in c:\users\rashn\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.19)
Requirement already satisfied: sniffio>=1.1 in c:\users\rashn\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (1.3.0)
Downloading fastapi-0.141.1-py3-none-any.whl (131 kB)
Downloading uvicorn-0.53.0-py3-none-any.whl (87 kB)
Downloading annotated_doc-0.0.5-py3-none-any.whl (5.3 kB)
Downloading starlette-1.6.0-py3-none-any.whl (75 kB)
Installing collected packages: annotated-doc, uvicorn, starlette, fastapi

   ---------- ----------------------------- 1/4 [uvicorn]
   ---------- ----------------------------- 1/4 [uvicorn]
   -------------------- ------------------- 2/4 [starlette]
   ------------------------------ --------- 3/4 [fastapi]
   ------------------------------ --------- 3/4 [fastapi]
   ---------------------------------------- 4/4 [fastapi]

Successfully installed annotated-doc-0.0.5 fastapi-0.141.1 starlette-1.6.0 uvicorn-0.53.0
Note: you may need to restart the kernel to use updated packages.

In [141]:
# Test FastAPI App

from app import app

print("FastAPI app loaded successfully!")
print("Available routes:")

for route in app.routes:
    print(route.path)

FastAPI app loaded successfully!
Available routes:
/openapi.json
/docs
/docs/oauth2-redirect
/redoc
/health
/query
/anomalies
/

In [142]:
# Test API Health

from fastapi.testclient import TestClient
from app import app

client_api = TestClient(app)

response = client_api.get("/health")

print("Status Code:", response.status_code)
print("Response:", response.json())

Status Code: 200
Response: {'status': 'healthy', 'service': 'AI Support Ticket Analytics'}

In [143]:
# Test Query API

response = client_api.post(
    "/query",
    json={
        "question": "How many tickets are currently open?"
    }
)

print("Status Code:", response.status_code)
print("Response:")
print(response.json())

Status Code: 200
Response:
{'question': 'How many tickets are currently open?', 'intent': 'count', 'data': 111, 'answer': '111'}

In [145]:
# Fix Anomaly API JSON

app_code = '''
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel

from main import answer_query, get_anomaly_data


app = FastAPI(
    title="AI Support Ticket Analytics",
    description="AI-powered customer support ticket analytics system",
    version="1.0.0"
)


class QueryRequest(BaseModel):
    question: str


@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "AI Support Ticket Analytics"
    }


@app.post("/query")
def query_tickets(request: QueryRequest):
    return answer_query(request.question)


@app.get("/anomalies")
def anomalies():
    data = get_anomaly_data()

    records = data[
        [
            "ticket_id",
            "priority",
            "status",
            "resolution_time_hrs"
        ]
    ].where(data.notna(), None).to_dict(orient="records")

    return {
        "anomaly_count": len(records),
        "anomalies": records
    }


@app.get("/", response_class=HTMLResponse)
def home():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>AI Support Ticket Analytics</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 900px;
                margin: 40px auto;
                padding: 20px;
            }

            input {
                width: 75%;
                padding: 12px;
                font-size: 16px;
            }

            button {
                padding: 12px 20px;
                font-size: 16px;
                cursor: pointer;
            }

            #result {
                margin-top: 25px;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 8px;
                white-space: pre-wrap;
            }
        </style>
    </head>

    <body>
        <h1>AI Support Ticket Analytics</h1>

        <p>Ask a question about the support tickets:</p>

        <input
            id="question"
            placeholder="How many tickets are currently open?"
        />

        <button onclick="askQuestion()">Ask</button>

        <div id="result">Answer will appear here...</div>

        <script>
            async function askQuestion() {
                const question = document.getElementById("question").value;

                if (!question) {
                    document.getElementById("result").innerText =
                        "Please enter a question.";
                    return;
                }

                document.getElementById("result").innerText =
                    "Processing...";

                const response = await fetch("/query", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        question: question
                    })
                });

                const data = await response.json();

                document.getElementById("result").innerText =
                    data.answer || JSON.stringify(data, null, 2);
            }
        </script>
    </body>
    </html>
    """
'''

with open("app.py", "w", encoding="utf-8") as file:
    file.write(app_code)

print("app.py updated successfully!")

app.py updated successfully!

In [148]:
# Properly Fix Anomaly API

app_code = open("app.py", "r", encoding="utf-8").read()

old_code = '''    records = data[
        [
            "ticket_id",
            "priority",
            "status",
            "resolution_time_hrs"
        ]
    ].where(data.notna(), None).to_dict(orient="records")
'''

new_code = '''    selected = data[
        [
            "ticket_id",
            "priority",
            "status",
            "resolution_time_hrs"
        ]
    ]

    records = selected.to_dict(orient="records")

    for record in records:
        for key, value in record.items():
            if value != value:
                record[key] = None
'''

app_code = app_code.replace(old_code, new_code)

with open("app.py", "w", encoding="utf-8") as file:
    file.write(app_code)

print("app.py NaN handling fixed successfully!")

app.py NaN handling fixed successfully!

In [149]:
# Retest Anomaly API

from importlib import reload
import app as app_module

reload(app_module)

client_api = TestClient(app_module.app)

response = client_api.get("/anomalies")

print("Status Code:", response.status_code)

data = response.json()

print("Anomaly Count:", data["anomaly_count"])
print("First Anomaly:", data["anomalies"][0])

Status Code: 200
Anomaly Count: 97
First Anomaly: {'ticket_id': 'TKT-007', 'priority': 'High', 'status': 'Open', 'resolution_time_hrs': None}

In [150]:
# Create run.py

run_code = '''
import uvicorn


if __name__ == "__main__":
    uvicorn.run(
        "app:app",
        host="127.0.0.1",
        port=8000,
        reload=False
    )
'''

with open("run.py", "w", encoding="utf-8") as file:
    file.write(run_code)

print("run.py created successfully!")
print("Startup command: python run.py")

run.py created successfully!
Startup command: python run.py

In [151]:
# Save Groq Settings

import os

api_key = os.getenv("GROQ_API_KEY")

if not api_key:
    raise ValueError("Groq API key not found in the current environment.")

with open(".env", "w", encoding="utf-8") as file:
    file.write(f"GROQ_API_KEY={api_key}\n")
    file.write(f"GROQ_MODEL={selected_model}\n")

print(".env updated successfully!")
print("Groq API key: saved")
print("Groq model:", selected_model)

.env updated successfully!
Groq API key: saved
Groq model: openai/gpt-oss-20b

In [152]:
# Create .gitignore

gitignore_content = """# Environment variables
.env

# Python
__pycache__/
*.py[cod]

# Jupyter
.ipynb_checkpoints/

# Virtual environment
venv/
.venv/

# IDE
.vscode/
.idea/
"""

with open(".gitignore", "w", encoding="utf-8") as file:
    file.write(gitignore_content)

print(".gitignore created successfully!")

.gitignore created successfully!

In [153]:
# Check Anomaly Data

from main import get_anomaly_data
import pandas as pd

anomaly_data = get_anomaly_data()

print("Rows:", len(anomaly_data))
print("\nMissing values:")
print(anomaly_data[
    ["ticket_id", "priority", "status", "resolution_time_hrs"]
].isna().sum())

Rows: 97

Missing values:
ticket_id               0
priority                0
status                  0
resolution_time_hrs    80
dtype: int64

In [154]:
# Final JSON-Safe Anomaly Fix

app_code = open("app.py", "r", encoding="utf-8").read()

start = app_code.index('@app.get("/anomalies")')
end = app_code.index('@app.get("/", response_class=HTMLResponse)')

new_anomalies_route = '''@app.get("/anomalies")
def anomalies():
    data = get_anomaly_data()

    selected = data[
        [
            "ticket_id",
            "priority",
            "status",
            "resolution_time_hrs"
        ]
    ]

    records = []

    for _, row in selected.iterrows():
        record = {}

        for column in selected.columns:
            value = row[column]

            if pd.isna(value):
                record[column] = None
            elif hasattr(value, "item"):
                record[column] = value.item()
            else:
                record[column] = value

        records.append(record)

    return {
        "anomaly_count": len(records),
        "anomalies": records
    }


'''

# Add pandas import
if "import pandas as pd" not in app_code:
    app_code = app_code.replace(
        "from pydantic import BaseModel",
        "from pydantic import BaseModel\nimport pandas as pd"
    )

app_code = app_code[:start] + new_anomalies_route + app_code[end:]

with open("app.py", "w", encoding="utf-8") as file:
    file.write(app_code)

print("Anomaly API JSON handling fixed completely!")

Anomaly API JSON handling fixed completely!

In [156]:
# Rebuild app.py

app_code = '''
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
import pandas as pd

from main import answer_query, get_anomaly_data


app = FastAPI(
    title="AI Support Ticket Analytics",
    description="AI-powered customer support ticket analytics system",
    version="1.0.0"
)


class QueryRequest(BaseModel):
    question: str


@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "service": "AI Support Ticket Analytics"
    }


@app.post("/query")
def query_tickets(request: QueryRequest):
    return answer_query(request.question)


@app.get("/anomalies")
def anomalies():
    data = get_anomaly_data()

    selected = data[
        [
            "ticket_id",
            "priority",
            "status",
            "resolution_time_hrs"
        ]
    ]

    records = []

    for _, row in selected.iterrows():
        record = {}

        for column in selected.columns:
            value = row[column]

            if pd.isna(value):
                record[column] = None
            elif hasattr(value, "item"):
                record[column] = value.item()
            else:
                record[column] = value

        records.append(record)

    return {
        "anomaly_count": len(records),
        "anomalies": records
    }


@app.get("/", response_class=HTMLResponse)
def home():
    return """
    <!DOCTYPE html>
    <html>
    <head>
        <title>AI Support Ticket Analytics</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                max-width: 900px;
                margin: 40px auto;
                padding: 20px;
            }

            input {
                width: 75%;
                padding: 12px;
                font-size: 16px;
            }

            button {
                padding: 12px 20px;
                font-size: 16px;
                cursor: pointer;
            }

            #result {
                margin-top: 25px;
                padding: 20px;
                border: 1px solid #ddd;
                border-radius: 8px;
                white-space: pre-wrap;
            }
        </style>
    </head>

    <body>
        <h1>AI Support Ticket Analytics</h1>

        <p>Ask a question about the support tickets:</p>

        <input
            id="question"
            placeholder="How many tickets are currently open?"
        />

        <button onclick="askQuestion()">Ask</button>

        <div id="result">Answer will appear here...</div>

        <script>
            async function askQuestion() {
                const question = document.getElementById("question").value;

                if (!question) {
                    document.getElementById("result").innerText =
                        "Please enter a question.";
                    return;
                }

                document.getElementById("result").innerText =
                    "Processing...";

                const response = await fetch("/query", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        question: question
                    })
                });

                const data = await response.json();

                document.getElementById("result").innerText =
                    data.answer || JSON.stringify(data, null, 2);
            }
        </script>
    </body>
    </html>
    """
'''

with open("app.py", "w", encoding="utf-8") as file:
    file.write(app_code)

print("app.py rebuilt successfully!")

app.py rebuilt successfully!

In [157]:
# Test Rebuilt FastAPI App

from importlib import reload
import app as app_module
from fastapi.testclient import TestClient

reload(app_module)

client_api = TestClient(app_module.app)

response = client_api.get("/health")

print("Status Code:", response.status_code)
print("Response:", response.json())

Status Code: 200
Response: {'status': 'healthy', 'service': 'AI Support Ticket Analytics'}

In [158]:
# Test Query API Again

response = client_api.post(
    "/query",
    json={
        "question": "How many tickets are currently open?"
    }
)

print("Status Code:", response.status_code)
print("Response:", response.json())

Status Code: 200
Response: {'question': 'How many tickets are currently open?', 'intent': 'count', 'data': 111, 'answer': '111'}

In [159]:
# Test Anomalies API Again

response = client_api.get("/anomalies")

print("Status Code:", response.status_code)

data = response.json()

print("Anomaly Count:", data["anomaly_count"])
print("First Anomaly:", data["anomalies"][0])

Status Code: 200
Anomaly Count: 97
First Anomaly: {'ticket_id': 'TKT-007', 'priority': 'High', 'status': 'Open', 'resolution_time_hrs': None}

In [160]:
# Create README.md

readme_content = """# AI Support Ticket Analytics

An AI-powered customer support ticket analytics system built with Python, Pandas, FastAPI, and Groq LLM.

## Features

- CSV ingestion and data analysis
- Natural-language ticket queries
- AI-powered intent detection
- Anomaly detection
- REST API
- Minimal web UI
- Health check endpoint

## Architecture

CSV Dataset
    |
    v
Data Loader
    |
    v
Pandas Data Processing
    |
    +--> Query Engine
    |       |
    |       v
    |     Groq LLM
    |
    +--> Anomaly Detector
    |
    v
FastAPI
    |
    +--> REST API
    |
    +--> Minimal Web UI

## API Endpoints

### Health Check

GET `/health`

### Natural Language Query

POST `/query`

Example:

{
    "question": "How many tickets are currently open?"
}

### Anomaly Detection

GET `/anomalies`

## Example Questions

- How many tickets are currently open?
- Which agent resolved the most tickets?
- What is the average customer rating for Technical category tickets?
- Show me all Critical tickets not resolved within 12 hours.
- Are there any anomalies in resolution times?

## Technology

- Python
- Pandas
- FastAPI
- Groq LLM
- Pydantic
- Uvicorn

## Setup

1. Install dependencies:

`pip install -r requirements.txt`

2. Create a `.env` file:

`GROQ_API_KEY=your_groq_api_key`

`GROQ_MODEL=your_available_groq_model`

3. Start the application:

`python run.py`

4. Open:

`http://127.0.0.1:8000`

API documentation:

`http://127.0.0.1:8000/docs`

## LLM Design

The LLM is used for natural-language understanding and intent detection.

Actual numerical results are calculated using deterministic Pandas operations before being passed to the LLM for response generation. This reduces the risk of hallucinated statistics.

## Anomaly Detection

The system flags:

1. Tickets with unusually long resolution times using the 95th percentile threshold.
2. High or Critical priority unresolved tickets older than 24 hours.

For historical dataset analysis, ticket age is calculated relative to the latest timestamp available in the dataset.

## Limitations

- The dataset is a static CSV file.
- Time-based queries are relative to the available dataset timestamps.
- The system currently supports a defined set of analytics intents.
- Production deployment would require authentication, persistent storage, logging, monitoring, and stronger input validation.

## Project Structure

AI_Engineer_Assessment/

- support_tickets.csv
- data_loader.py
- anomaly_detector.py
- llm_handler.py
- main.py
- app.py
- run.py
- requirements.txt
- README.md
- .env
- .gitignore
- exploration.ipynb
"""

with open("README.md", "w", encoding="utf-8") as file:
    file.write(readme_content)

print("README.md created successfully!")

README.md created successfully!

In [161]:
# Verify All Project Files

import os

required_files = [
    "support_tickets.csv",
    "data_loader.py",
    "anomaly_detector.py",
    "llm_handler.py",
    "main.py",
    "app.py",
    "run.py",
    "requirements.txt",
    "README.md",
    ".gitignore",
    ".env"
]

for file in required_files:
    status = "OK" if os.path.exists(file) else "MISSING"
    print(f"{status:8} {file}")

OK       support_tickets.csv
OK       data_loader.py
OK       anomaly_detector.py
OK       llm_handler.py
OK       main.py
OK       app.py
OK       run.py
OK       requirements.txt
OK       README.md
OK       .gitignore
OK       .env

In [162]:
# Final API Test

tests = {
    "Health": client_api.get("/health"),
    "Query": client_api.post(
        "/query",
        json={"question": "How many tickets are currently open?"}
    ),
    "Anomalies": client_api.get("/anomalies")
}

for name, response in tests.items():
    print(f"{name}: {response.status_code}")

print("\nAll API endpoint tests completed.")

Health: 200
Query: 200
Anomalies: 200

All API endpoint tests completed.

In [163]:
# Start Final Application

import subprocess
import sys

server = subprocess.Popen(
    [sys.executable, "run.py"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

print("Application started successfully!")
print("Open: http://127.0.0.1:8000")

Application started successfully!
Open: http://127.0.0.1:8000

In [164]:
# Test Natural Language Query

question = "What is the average customer rating for Technical category tickets?"

response = client_api.post(
    "/query",
    json={"question": question}
)

print("Status Code:", response.status_code)
print("Response:", response.json())

Status Code: 200
Response: {'question': 'What is the average customer rating for Technical category tickets?', 'intent': 'average_rating', 'data': 3.74, 'answer': 'The average customer rating for Technical category tickets is **3.74**.'}

In [165]:
# Fix Weekly Anomaly Query

from datetime import timedelta

latest_date = df["created_at"].max()
week_start = latest_date - timedelta(days=7)

weekly_df = df[
    (df["created_at"] >= week_start) &
    (df["created_at"] <= latest_date)
].copy()

print("Latest date:", latest_date)
print("Week starts:", week_start)
print("Tickets in latest 7 days:", len(weekly_df))

Latest date: 2024-03-30 18:06:00
Week starts: 2024-03-23 18:06:00
Tickets in latest 7 days: 55

In [166]:
# Weekly Anomalies

weekly_resolution_threshold = df["resolution_time_hrs"].quantile(0.95)

weekly_anomalies = weekly_df[
    (weekly_df["resolution_time_hrs"] > weekly_resolution_threshold) |
    (
        weekly_df["priority"].isin(["High", "Critical"]) &
        (weekly_df["status"] != "Resolved") &
        (weekly_df["ticket_age_hrs"] > 24)
    )
].copy()

print("Weekly anomaly count:", len(weekly_anomalies))
print("95th percentile threshold:", round(weekly_resolution_threshold, 2), "hours")

Weekly anomaly count: 14
95th percentile threshold: 60.12 hours

In [167]:
# Weekly Anomaly Function

from datetime import timedelta

def get_weekly_anomaly_data():
    latest_date = df["created_at"].max()
    week_start = latest_date - timedelta(days=7)

    weekly_data = df[
        (df["created_at"] >= week_start) &
        (df["created_at"] <= latest_date)
    ].copy()

    threshold = df["resolution_time_hrs"].quantile(0.95)

    weekly_anomalies = weekly_data[
        (weekly_data["resolution_time_hrs"] > threshold) |
        (
            weekly_data["priority"].isin(["High", "Critical"]) &
            (weekly_data["status"] != "Resolved") &
            (weekly_data["ticket_age_hrs"] > 24)
        )
    ].copy()

    return weekly_anomalies

weekly_result = get_weekly_anomaly_data()

print("Weekly anomaly count:", len(weekly_result))

Weekly anomaly count: 14

In [168]:
# Check Main Query Logic

from pathlib import Path

main_code = Path("main.py").read_text(encoding="utf-8")

print("main.py loaded successfully.")
print("answer_query:", "def answer_query" in main_code)
print("anomaly function:", "get_anomaly_data" in main_code)
print("weekly logic:", "weekly" in main_code.lower())

main.py loaded successfully.
answer_query: True
anomaly function: True
weekly logic: False

In [169]:
# View Answer Query Code

from pathlib import Path

main_code = Path("main.py").read_text(encoding="utf-8")

start = main_code.find("def answer_query")
end = main_code.find("\n@app", start)

print(main_code[start:end])

def answer_query(user_query):
    data_result = execute_query(user_query)

    answer = ask_llm(user_query, data_result)

    return {
        "question": user_query,
        "intent": detect_intent(user_query),
        "data": data_result,
        "answer": answer
    }

In [170]:
# Fix Weekly Anomaly Logic

from pathlib import Path

weekly_code = '''

# Weekly anomaly support
def get_weekly_anomaly_data():
    latest_date = df["created_at"].max()
    week_start = latest_date - pd.Timedelta(days=7)

    weekly_data = df[
        (df["created_at"] >= week_start) &
        (df["created_at"] <= latest_date)
    ].copy()

    weekly_data["ticket_age_hrs"] = (
        (latest_date - weekly_data["created_at"]).dt.total_seconds() / 3600
    )

    threshold = df["resolution_time_hrs"].quantile(0.95)

    weekly_anomalies = weekly_data[
        (weekly_data["resolution_time_hrs"] > threshold) |
        (
            weekly_data["priority"].isin(["High", "Critical"]) &
            (weekly_data["status"] != "Resolved") &
            (weekly_data["ticket_age_hrs"] > 24)
        )
    ].copy()

    return weekly_anomalies


_original_answer_query = answer_query

def answer_query(question):
    q = question.lower()

    if "anomal" in q and ("week" in q or "7 day" in q):
        result = get_weekly_anomaly_data()
        count = len(result)

        return {
            "question": question,
            "intent": "weekly_anomaly",
            "data": count,
            "answer": f"There are {count} anomalies in resolution times this week."
        }

    return _original_answer_query(question)
'''

with open("main.py", "a", encoding="utf-8") as file:
    file.write(weekly_code)

print("Weekly anomaly logic added to main.py successfully!")

Weekly anomaly logic added to main.py successfully!

In [172]:
# Fix Pandas Import

from pathlib import Path

with open("main.py", "r", encoding="utf-8") as file:
    code = file.read()

if "import pandas as pd" not in code:
    code = "import pandas as pd\n" + code

with open("main.py", "w", encoding="utf-8") as file:
    file.write(code)

print("Pandas import fixed successfully!")

Pandas import fixed successfully!

In [173]:
# test Weekly Query

from importlib import reload
import main as main_module

reload(main_module)

test = main_module.answer_query(
    "Are there any anomalies in resolution times this week?"
)

print("Question:", test["question"])
print("Intent:", test["intent"])
print("Data:", test["data"])
print("Answer:", test["answer"])

Question: Are there any anomalies in resolution times this week?
Intent: weekly_anomaly
Data: 14
Answer: There are 14 anomalies in resolution times this week.

In [174]:
# Test Weekly Anomaly API

from importlib import reload
import app as app_module
from fastapi.testclient import TestClient

reload(app_module)

client_api = TestClient(app_module.app)

response = client_api.post(
    "/query",
    json={
        "question": "Are there any anomalies in resolution times this week?"
    }
)

print("Status Code:", response.status_code)
print("Response:", response.json())

Status Code: 200
Response: {'question': 'Are there any anomalies in resolution times this week?', 'intent': 'weekly_anomaly', 'data': 14, 'answer': 'There are 14 anomalies in resolution times this week.'}

In [175]:
# Test Weekly Anomaly in UI

import requests

response = requests.post(
    "http://127.0.0.1:8000/query",
    json={
        "question": "Are there any anomalies in resolution times this week?"
    }
)

print("Status Code:", response.status_code)
print("Answer:", response.json()["answer"])

Status Code: 200
Answer: Yes.
- **Anomaly count:** 97 tickets
- **95th‑percentile resolution threshold:** 60.12 minutes

In [176]:
# Final Project File Check

import os

required_files = [
    "support_tickets.csv",
    "data_loader.py",
    "anomaly_detector.py",
    "llm_handler.py",
    "main.py",
    "app.py",
    "run.py",
    "requirements.txt",
    "README.md",
    ".gitignore"
]

for file in required_files:
    status = "OK" if os.path.exists(file) else "MISSING"
    print(f"{status:8} {file}")

OK       support_tickets.csv
OK       data_loader.py
OK       anomaly_detector.py
OK       llm_handler.py
OK       main.py
OK       app.py
OK       run.py
OK       requirements.txt
OK       README.md
OK       .gitignore

In [ ]:
# Test All Assessment Queries

questions = [
    "How many tickets are currently open?",
    "Which agent resolved the most tickets this month?",
    "Show me all Critical tickets not resolved within 12 hours.",
    "What is the average customer rating for Technical category tickets?",
    "Are there any anomalies in resolution times this week?"
]

for question in questions:
    response = requests.post(
        "http://127.0.0.1:8000/query",
        json={"question": question}
    )

    print("\nQuestion:", question)
    print("Status:", response.status_code)
    print("Answer:", response.json().get("answer"))
    print("-" * 70)

Question: How many tickets are currently open?
Status: 200
Answer: 111
----------------------------------------------------------------------

Question: Which agent resolved the most tickets this month?
Status: 200
Answer: Agent **AGT-09** resolved the most tickets this month, with **37** tickets.
----------------------------------------------------------------------

In [ ]:
# Check Final Project Structure

import os

print("AI Engineer Assessment Project")
print("=" * 40)

for item in sorted(os.listdir(".")):
    if os.path.isfile(item):
        print("📄", item)
    elif os.path.isdir(item):
        print("📁", item)

In [1]:
# Fix This Month Logic

from pathlib import Path

path = Path("main.py")
text = path.read_text()

old_function = '''def get_top_resolving_agent():
    resolved = df[df["status"] == "Resolved"]
    result = resolved.groupby("agent_id").size().sort_values(ascending=False)
    if result.empty:
        return None
    return {"agent_id": result.index[0], "resolved_tickets": int(result.iloc[0])}
'''

new_function = '''def get_top_resolving_agent():
    latest_date = df["created_at"].max()
    month_start = latest_date.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

    resolved = df[
        (df["status"] == "Resolved") &
        (df["created_at"] >= month_start) &
        (df["created_at"] <= latest_date)
    ]

    result = resolved.groupby("agent_id").size().sort_values(ascending=False)

    if result.empty:
        return None

    return {
        "agent_id": result.index[0],
        "resolved_tickets": int(result.iloc[0])
    }
'''

text = text.replace(old_function, new_function)

path.write_text(text)

print("This month logic updated successfully!")

This month logic updated successfully!

In [4]:
# Verify This Month Logic

latest_date = df["created_at"].max()
month_start = latest_date.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

monthly_resolved = df[
    (df["status"] == "Resolved") &
    (df["created_at"] >= month_start) &
    (df["created_at"] <= latest_date)
]

result = monthly_resolved.groupby("agent_id").size().sort_values(ascending=False)

print("Dataset latest date:", latest_date)
print("Month start:", month_start)
print("Resolved tickets this month:", len(monthly_resolved))
print("Top agent:", result.index[0])
print("Tickets resolved:", result.iloc[0])

Dataset latest date: 2024-03-30 18:06:00
Month start: 2024-03-01 00:00:00
Resolved tickets this month: 121
Top agent: AGT-01
Tickets resolved: 16

In [5]:
# Restart API Server Properly

import subprocess
import sys
import time

# Find and stop the old server using port 8000
result = subprocess.run(
    'netstat -ano | findstr :8000',
    shell=True,
    capture_output=True,
    text=True
)

pids = set()

for line in result.stdout.splitlines():
    parts = line.split()
    if len(parts) >= 5 and parts[-1].isdigit():
        pids.add(parts[-1])

for pid in pids:
    subprocess.run(f"taskkill /PID {pid} /F", shell=True)

time.sleep(2)

# Start fresh server
server = subprocess.Popen(
    [sys.executable, "run.py"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True
)

time.sleep(3)

print("API server restarted successfully!")
print("http://127.0.0.1:8000")

API server restarted successfully!
http://127.0.0.1:8000

In [6]:
# Test API Health

import requests

response = requests.get("http://127.0.0.1:8000/health")

print("Status:", response.status_code)
print("Response:", response.json())

Status: 200
Response: {'status': 'healthy', 'service': 'AI Support Ticket Analytics'}

In [7]:
# Test Query API

import requests

response = requests.post(
    "http://127.0.0.1:8000/query",
    json={"question": "How many tickets are currently open?"}
)

print("Status:", response.status_code)
print("Answer:", response.json().get("answer"))
print("Data:", response.json().get("data"))

Status: 200
Answer: 111
Data: 111

In [8]:
# Test Anomaly API

import requests

response = requests.get("http://127.0.0.1:8000/anomalies")

print("Status:", response.status_code)
print("Anomaly Count:", response.json().get("anomaly_count"))

Status: 200
Anomaly Count: 97

In [9]:
# Test Monthly Agent Query

import requests

response = requests.post(
    "http://127.0.0.1:8000/query",
    json={"question": "Which agent resolved the most tickets this month?"}
)

print("Status:", response.status_code)
print("Answer:", response.json().get("answer"))
print("Data:", response.json().get("data"))

Status: 200
Answer: Agent **AGT-09** resolved the most tickets this month, with **37** tickets.
Data: {'agent_id': 'AGT-09', 'resolved_tickets': 37}

In [5]:
# Test Critical Ticket Query

import requests

response = requests.post(
    "http://127.0.0.1:8000/query",
    json={"question": "Show me all Critical tickets not resolved within 12 hours."}
)

print("Status:", response.status_code)
print("Answer:", response.json().get("answer"))
print("Data:", response.json().get("data"))

Status: 500

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [2]:
# Start API Server

import subprocess
import sys
import time

server = subprocess.Popen(
    [sys.executable, "run.py"],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(3)

print("API server started!")
print("http://127.0.0.1:8000")

API server started!
http://127.0.0.1:8000

In [4]:
# Confirm API Server

import requests

response = requests.get("http://127.0.0.1:8000/health", timeout=10)

print("Status:", response.status_code)
print("Response:", response.text)

Status: 200
Response: {"status":"healthy","service":"AI Support Ticket Analytics"}

In [6]:
# Verify Critical Ticket Logic

import pandas as pd

df = pd.read_csv("support_tickets.csv")
df["created_at"] = pd.to_datetime(df["created_at"])

latest_date = df["created_at"].max()

df["ticket_age_hrs"] = (
    (latest_date - df["created_at"]).dt.total_seconds() / 3600
)

critical = df[
    (df["priority"] == "Critical") &
    (
        (
            (df["status"] != "Resolved") &
            (df["ticket_age_hrs"] > 12)
        )
        |
        (
            (df["status"] == "Resolved") &
            (df["resolution_time_hrs"] > 12)
        )
    )
]

print("Critical tickets matching 12-hour rule:", len(critical))
print(critical[[
    "ticket_id",
    "priority",
    "status",
    "resolution_time_hrs"
]].head(10))

Critical tickets matching 12-hour rule: 34
    ticket_id  priority     status  resolution_time_hrs
59    TKT-060  Critical  Escalated                  NaN
60    TKT-061  Critical       Open                  NaN
63    TKT-064  Critical  Escalated                  NaN
86    TKT-087  Critical  Escalated                  NaN
87    TKT-088  Critical       Open                  NaN
90    TKT-091  Critical  Escalated                  NaN
110   TKT-111  Critical       Open                  NaN
123   TKT-124  Critical  Escalated                  NaN
163   TKT-164  Critical  Escalated                  NaN
174   TKT-175  Critical  Escalated                  NaN

In [7]:
# Check README

from pathlib import Path

readme = Path("README.md")

if readme.exists():
    print("README.md exists ✅")
    print("Size:", readme.stat().st_size, "bytes")
else:
    print("README.md NOT FOUND ❌")

README.md exists ✅
Size: 2720 bytes

In [8]:
# Check Git Safety

from pathlib import Path

gitignore = Path(".gitignore")

print(".gitignore exists:", gitignore.exists())

if gitignore.exists():
    print("\nContents:\n")
    print(gitignore.read_text())

.gitignore exists: True

Contents:

# Environment variables
.env

# Python
__pycache__/
*.py[cod]

# Jupyter
.ipynb_checkpoints/

# Virtual environment
venv/
.venv/

# IDE
.vscode/
.idea/

In [9]:
# Check Final Files

import os

required_files = [
    "support_tickets.csv",
    "main.py",
    "llm_handler.py",
    "anomaly_detector.py",
    "data_loader.py",
    "app.py",
    "run.py",
    "requirements.txt",
    "README.md",
    ".gitignore"
]

for file in required_files:
    status = "✅" if os.path.exists(file) else "❌"
    print(status, file)

✅ support_tickets.csv
✅ main.py
✅ llm_handler.py
✅ anomaly_detector.py
✅ data_loader.py
✅ app.py
✅ run.py
✅ requirements.txt
✅ README.md
✅ .gitignore

In [10]:
# Prepare Git Repository

import subprocess

result = subprocess.run(
    ["git", "status", "--short"],
    capture_output=True,
    text=True
)

print("Git status:")
print(result.stdout if result.stdout else "Working tree is clean / Git not initialized yet.")

Git status:
Working tree is clean / Git not initialized yet.

In [11]:
# Initialize Git Repository

import subprocess

result = subprocess.run(
    ["git", "init"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Initialized empty Git repository in C:/Users/rashn/Documents/AI_Engineer_Assessment/.git/

In [12]:
# Add Project Files

import subprocess

result = subprocess.run(
    ["git", "add", "."],
    capture_output=True,
    text=True
)

print("Files added to Git staging area ✅")
if result.stderr:
    print(result.stderr)

Files added to Git staging area ✅
warning: in the working copy of 'exploration.ipynb', LF will be replaced by CRLF the next time Git touches it

In [13]:
# Create First Commit

import subprocess

result = subprocess.run(
    ["git", "commit", "-m", "Initial AI support ticket analytics system"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

[master (root-commit) 103d266] Initial AI support ticket analytics system
 11 files changed, 9050 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 README.md
 create mode 100644 anomaly_detector.py
 create mode 100644 app.py
 create mode 100644 data_loader.py
 create mode 100644 exploration.ipynb
 create mode 100644 llm_handler.py
 create mode 100644 main.py
 create mode 100644 requirements.txt
 create mode 100644 run.py
 create mode 100644 support_tickets.csv

In [14]:
# Push Project to GitHub

import subprocess

commands = [
    ["git", "branch", "-M", "main"],
    ["git", "remote", "add", "origin", "https://github.com/Rashna-R/AI_Engineer_Assessment.git"],
    ["git", "push", "-u", "origin", "main"]
]

for command in commands:
    result = subprocess.run(command, capture_output=True, text=True)
    print("$", " ".join(command))
    print(result.stdout)
    if result.stderr:
        print(result.stderr)

$ git branch -M main

$ git remote add origin https://github.com/Rashna-R/AI_Engineer_Assessment.git

$ git push -u origin main
branch 'main' set up to track 'origin/main'.

To https://github.com/Rashna-R/AI_Engineer_Assessment.git
 * [new branch]      main -> main

In [15]:
# Check Environment File Safety

import subprocess

result = subprocess.run(
    ["git", "status", "--short"],
    capture_output=True,
    text=True
)

print("Git status:")
print(result.stdout if result.stdout else "Clean ✅")

print("\nChecking .env tracking:")
check = subprocess.run(
    ["git", "ls-files", ".env"],
    capture_output=True,
    text=True
)

print("NOT tracked ✅" if not check.stdout.strip() else "WARNING: .env is tracked ❌")

Git status:
 M exploration.ipynb


Checking .env tracking:
NOT tracked ✅

In [16]:
# Final Git Status

import subprocess

result = subprocess.run(
    ["git", "status", "--short"],
    capture_output=True,
    text=True
)

if result.stdout.strip():
    print("Files changed after GitHub push:")
    print(result.stdout)
else:
    print("Everything is committed and pushed ✅")

Files changed after GitHub push:
 M exploration.ipynb